[workspace]
resolver = "2"
members = [
    "src-tauri",
    "packages/driver-api",
    "packages/ai-api",
]
exclude = [
    ".plugins/kiwi",
    ".plugins/olap",
    ".plugins/superset",
]

[profile.dev]
incremental = true

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "s"

[patch."https://github.com/flyxl/datazen-driver-api.git"]
datazen-driver-api = { path = "packages/driver-api" }

[patch."https://github.com/flyxl/datazen-plugin-kiwi.git"]
datazen-plugin-kiwi = { path = ".plugins/kiwi" }

[patch."https://github.com/flyxl/datazen-plugin-olap.git"]
datazen-plugin-olap = { path = ".plugins/olap" }
