/**
 * Static Redis command metadata for the Console completion popup (R11).
 * `group` uses Redis' official command categories; `syntax` is the argument
 * skeleton; `desc` is a one-line English reference string (command content, not
 * app chrome). Replaces the bare name array in `redisCommands.ts` for completion.
 */

export type CommandGroup =
  | 'string'
  | 'hash'
  | 'list'
  | 'set'
  | 'zset'
  | 'geo'
  | 'stream'
  | 'generic'
  | 'keyspace'
  | 'server'
  | 'pubsub'
  | 'script'
  | 'cluster'
  | 'connection'
  | 'bitmap';

export interface CommandMeta {
  name: string;
  group: CommandGroup;
  syntax: string;
  desc: string;
}

export const REDIS_COMMAND_META: readonly CommandMeta[] = [
  {
    name: 'ACL',
    group: 'server',
    syntax: 'ACL [cat|list|user ...]',
    desc: 'Inspect and manage Access Control List users and rules',
  },
  {
    name: 'APPEND',
    group: 'string',
    syntax: 'APPEND key value',
    desc: 'Append a string to the value of a key, creating it if missing',
  },
  {
    name: 'AUTH',
    group: 'connection',
    syntax: 'AUTH [username] password',
    desc: 'Authenticate the connection with a password',
  },
  {
    name: 'BGREWRITEAOF',
    group: 'server',
    syntax: 'BGREWRITEAOF',
    desc: 'Asynchronously rewrite the append-only file',
  },
  {
    name: 'BGSAVE',
    group: 'server',
    syntax: 'BGSAVE [SCHEDULE]',
    desc: 'Asynchronously save the dataset to disk',
  },
  {
    name: 'BITCOUNT',
    group: 'bitmap',
    syntax: 'BITCOUNT key [start end [BYTE|BIT]]',
    desc: 'Count set bits in a string',
  },
  {
    name: 'BITFIELD',
    group: 'bitmap',
    syntax: 'BITFIELD key [GET|SET|INCRBY ...]',
    desc: 'Get, set and increment strings as binary integer bitfields',
  },
  {
    name: 'CLIENT',
    group: 'connection',
    syntax: 'CLIENT [id|list|setname ...]',
    desc: 'Inspect and manipulate the connection the command is sent from',
  },
  {
    name: 'CLUSTER',
    group: 'cluster',
    syntax: 'CLUSTER [info|nodes|slots ...]',
    desc: 'Inspect and manipulate the Redis Cluster',
  },
  {
    name: 'CONFIG',
    group: 'server',
    syntax: 'CONFIG [GET|SET|REWRITE ...]',
    desc: 'Get and set configuration parameters at runtime',
  },
  {
    name: 'COPY',
    group: 'generic',
    syntax: 'COPY source destination [DB source-db]',
    desc: 'Copy a key to a new key',
  },
  {
    name: 'DBSIZE',
    group: 'keyspace',
    syntax: 'DBSIZE',
    desc: 'Return the number of keys in the current database',
  },
  {
    name: 'DECR',
    group: 'string',
    syntax: 'DECR key',
    desc: 'Decrement the integer value of a key by one',
  },
  {
    name: 'DECRBY',
    group: 'string',
    syntax: 'DECRBY key decrement',
    desc: 'Decrement the integer value of a key by the given amount',
  },
  { name: 'DEL', group: 'generic', syntax: 'DEL key [key ...]', desc: 'Delete one or more keys' },
  {
    name: 'DISCARD',
    group: 'script',
    syntax: 'DISCARD',
    desc: 'Flush all previously queued commands in a transaction',
  },
  {
    name: 'DUMP',
    group: 'generic',
    syntax: 'DUMP key',
    desc: 'Return a serialized version of the value stored at a key',
  },
  { name: 'ECHO', group: 'connection', syntax: 'ECHO message', desc: 'Echo the given string back' },
  {
    name: 'EVAL',
    group: 'script',
    syntax: 'EVAL script numkeys [key ...] [arg ...]',
    desc: 'Execute a Lua script server side',
  },
  {
    name: 'EVALSHA',
    group: 'script',
    syntax: 'EVALSHA sha1 numkeys [key ...] [arg ...]',
    desc: 'Execute a cached Lua script by its SHA1 digest',
  },
  {
    name: 'EXEC',
    group: 'script',
    syntax: 'EXEC',
    desc: 'Execute all previously queued commands in a transaction',
  },
  {
    name: 'EXISTS',
    group: 'generic',
    syntax: 'EXISTS key [key ...]',
    desc: 'Determine whether one or more keys exist',
  },
  {
    name: 'EXPIRE',
    group: 'generic',
    syntax: 'EXPIRE key seconds [NX|XX|GT|LT]',
    desc: 'Set a key to expire in a number of seconds',
  },
  {
    name: 'EXPIREAT',
    group: 'generic',
    syntax: 'EXPIREAT key timestamp',
    desc: 'Set a key to expire at an absolute UNIX time',
  },
  {
    name: 'FLUSHALL',
    group: 'keyspace',
    syntax: 'FLUSHALL [ASYNC|SYNC]',
    desc: 'Delete all keys in all databases',
  },
  {
    name: 'FLUSHDB',
    group: 'keyspace',
    syntax: 'FLUSHDB [ASYNC|SYNC]',
    desc: 'Delete all keys in the current database',
  },
  {
    name: 'GEOADD',
    group: 'geo',
    syntax: 'GEOADD key [NX|XX] [CH] longitude latitude member [...]',
    desc: 'Add geospatial items to a sorted set',
  },
  { name: 'GET', group: 'string', syntax: 'GET key', desc: 'Get the value of a string key' },
  {
    name: 'GETBIT',
    group: 'bitmap',
    syntax: 'GETBIT key offset',
    desc: 'Return the bit value at an offset in a string',
  },
  {
    name: 'GETDEL',
    group: 'string',
    syntax: 'GETDEL key',
    desc: 'Get the value of a key and delete it',
  },
  {
    name: 'GETEX',
    group: 'string',
    syntax: 'GETEX key [EX|PX|EXAT|PERSIST]',
    desc: 'Get a key and optionally set its expiration',
  },
  {
    name: 'GETRANGE',
    group: 'string',
    syntax: 'GETRANGE key start end',
    desc: 'Get a substring of the value stored at a key',
  },
  {
    name: 'GETSET',
    group: 'string',
    syntax: 'GETSET key value',
    desc: 'Set a key and return its old value (deprecated)',
  },
  {
    name: 'HDEL',
    group: 'hash',
    syntax: 'HDEL key field [field ...]',
    desc: 'Delete one or more hash fields',
  },
  {
    name: 'HEXISTS',
    group: 'hash',
    syntax: 'HEXISTS key field',
    desc: 'Determine whether a hash field exists',
  },
  { name: 'HGET', group: 'hash', syntax: 'HGET key field', desc: 'Get the value of a hash field' },
  {
    name: 'HGETALL',
    group: 'hash',
    syntax: 'HGETALL key',
    desc: 'Get all fields and values in a hash',
  },
  {
    name: 'HINCRBY',
    group: 'hash',
    syntax: 'HINCRBY key field increment',
    desc: 'Increment the integer value of a hash field',
  },
  {
    name: 'HINCRBYFLOAT',
    group: 'hash',
    syntax: 'HINCRBYFLOAT key field increment',
    desc: 'Increment the float value of a hash field',
  },
  { name: 'HKEYS', group: 'hash', syntax: 'HKEYS key', desc: 'Get all the field names in a hash' },
  { name: 'HLEN', group: 'hash', syntax: 'HLEN key', desc: 'Get the number of fields in a hash' },
  {
    name: 'HMGET',
    group: 'hash',
    syntax: 'HMGET key field [field ...]',
    desc: 'Get the values of multiple hash fields',
  },
  {
    name: 'HMSET',
    group: 'hash',
    syntax: 'HMSET key field value [field value ...]',
    desc: 'Set multiple hash fields (deprecated, use HSET)',
  },
  {
    name: 'HSET',
    group: 'hash',
    syntax: 'HSET key field value [field value ...]',
    desc: 'Set one or more hash fields',
  },
  {
    name: 'HSETNX',
    group: 'hash',
    syntax: 'HSETNX key field value',
    desc: 'Set a hash field only if it does not exist',
  },
  {
    name: 'HSTRLEN',
    group: 'hash',
    syntax: 'HSTRLEN key field',
    desc: 'Get the length of the value of a hash field',
  },
  { name: 'HVALS', group: 'hash', syntax: 'HVALS key', desc: 'Get all the values in a hash' },
  {
    name: 'INCR',
    group: 'string',
    syntax: 'INCR key',
    desc: 'Increment the integer value of a key by one',
  },
  {
    name: 'INCRBY',
    group: 'string',
    syntax: 'INCRBY key increment',
    desc: 'Increment the integer value of a key by the given amount',
  },
  {
    name: 'INCRBYFLOAT',
    group: 'string',
    syntax: 'INCRBYFLOAT key increment',
    desc: 'Increment the float value of a key by the given amount',
  },
  {
    name: 'INFO',
    group: 'server',
    syntax: 'INFO [section]',
    desc: 'Return statistics and information about the server',
  },
  {
    name: 'KEYS',
    group: 'generic',
    syntax: 'KEYS pattern',
    desc: 'Find all keys matching a pattern (blocking on large datasets)',
  },
  {
    name: 'LASTSAVE',
    group: 'server',
    syntax: 'LASTSAVE',
    desc: 'Return the UNIX time of the last successful save to disk',
  },
  {
    name: 'LINDEX',
    group: 'list',
    syntax: 'LINDEX key index',
    desc: 'Get an element from a list by its index',
  },
  {
    name: 'LINSERT',
    group: 'list',
    syntax: 'LINSERT key BEFORE|AFTER pivot element',
    desc: 'Insert an element before or after another element in a list',
  },
  { name: 'LLEN', group: 'list', syntax: 'LLEN key', desc: 'Get the length of a list' },
  {
    name: 'LPOP',
    group: 'list',
    syntax: 'LPOP key [count]',
    desc: 'Remove and return the first elements of a list',
  },
  {
    name: 'LPUSH',
    group: 'list',
    syntax: 'LPUSH key element [element ...]',
    desc: 'Prepend one or more elements to a list',
  },
  {
    name: 'LPUSHX',
    group: 'list',
    syntax: 'LPUSHX key element [element ...]',
    desc: 'Prepend to a list only if the list exists',
  },
  {
    name: 'LRANGE',
    group: 'list',
    syntax: 'LRANGE key start stop',
    desc: 'Get a range of elements from a list',
  },
  {
    name: 'LREM',
    group: 'list',
    syntax: 'LREM key count element',
    desc: 'Remove elements from a list',
  },
  {
    name: 'LSET',
    group: 'list',
    syntax: 'LSET key index element',
    desc: 'Set the value of an element in a list by index',
  },
  {
    name: 'LTRIM',
    group: 'list',
    syntax: 'LTRIM key start stop',
    desc: 'Trim a list to the specified range',
  },
  {
    name: 'MEMORY',
    group: 'server',
    syntax: 'MEMORY [usage|doctor|stats ...]',
    desc: 'Inspect memory usage of keys and the server',
  },
  {
    name: 'MGET',
    group: 'string',
    syntax: 'MGET key [key ...]',
    desc: 'Get the values of multiple keys',
  },
  {
    name: 'MIGRATE',
    group: 'generic',
    syntax: 'MIGRATE host port key [AUTH2 KEYS ...]',
    desc: 'Atomically move a key to another database or node',
  },
  {
    name: 'MONITOR',
    group: 'server',
    syntax: 'MONITOR',
    desc: 'Listen for all requests received by the server in real time',
  },
  { name: 'MOVE', group: 'generic', syntax: 'MOVE key db', desc: 'Move a key to another database' },
  {
    name: 'MSET',
    group: 'string',
    syntax: 'MSET key value [key value ...]',
    desc: 'Set multiple keys to multiple values',
  },
  {
    name: 'MSETNX',
    group: 'string',
    syntax: 'MSETNX key value [key value ...]',
    desc: 'Set multiple keys only if none exist',
  },
  {
    name: 'MULTI',
    group: 'script',
    syntax: 'MULTI',
    desc: 'Mark the start of a transaction block',
  },
  {
    name: 'OBJECT',
    group: 'generic',
    syntax: 'OBJECT [ENCODING|IDLETIME|FREQ ...]',
    desc: 'Inspect the internal representation of a key',
  },
  {
    name: 'PERSIST',
    group: 'generic',
    syntax: 'PERSIST key',
    desc: 'Remove the expiration from a key',
  },
  {
    name: 'PEXPIRE',
    group: 'generic',
    syntax: 'PEXPIRE key milliseconds',
    desc: 'Set a key to expire in a number of milliseconds',
  },
  {
    name: 'PEXPIREAT',
    group: 'generic',
    syntax: 'PEXPIREAT key ms-timestamp',
    desc: 'Set a key to expire at an absolute millisecond time',
  },
  {
    name: 'PING',
    group: 'connection',
    syntax: 'PING [message]',
    desc: 'Check the connection and server liveness',
  },
  {
    name: 'PSETEX',
    group: 'string',
    syntax: 'PSETEX key milliseconds value',
    desc: 'Set a key with an expiry in milliseconds',
  },
  {
    name: 'PSUBSCRIBE',
    group: 'pubsub',
    syntax: 'PSUBSCRIBE pattern [pattern ...]',
    desc: 'Listen for messages on channels matching a pattern',
  },
  {
    name: 'PTTL',
    group: 'generic',
    syntax: 'PTTL key',
    desc: 'Get a key remaining time to live in milliseconds',
  },
  {
    name: 'PUBLISH',
    group: 'pubsub',
    syntax: 'PUBLISH channel message',
    desc: 'Post a message to a channel',
  },
  {
    name: 'PUNSUBSCRIBE',
    group: 'pubsub',
    syntax: 'PUNSUBSCRIBE [pattern ...]',
    desc: 'Stop listening for messages matching a pattern',
  },
  {
    name: 'RANDOMKEY',
    group: 'generic',
    syntax: 'RANDOMKEY',
    desc: 'Return a random key from the keyspace',
  },
  { name: 'RENAME', group: 'generic', syntax: 'RENAME key newkey', desc: 'Rename a key' },
  {
    name: 'RENAMENX',
    group: 'generic',
    syntax: 'RENAMENX key newkey',
    desc: 'Rename a key only if the target does not exist',
  },
  {
    name: 'RESTORE',
    group: 'generic',
    syntax: 'RESTORE key ttl serialized-value',
    desc: 'Deserialize a value and store it on a key',
  },
  {
    name: 'RPOP',
    group: 'list',
    syntax: 'RPOP key [count]',
    desc: 'Remove and return the last elements of a list',
  },
  {
    name: 'RPOPLPUSH',
    group: 'list',
    syntax: 'RPOPLPUSH source destination',
    desc: 'Atomically pop from a list and push to another',
  },
  {
    name: 'RPUSH',
    group: 'list',
    syntax: 'RPUSH key element [element ...]',
    desc: 'Append one or more elements to a list',
  },
  {
    name: 'RPUSHX',
    group: 'list',
    syntax: 'RPUSHX key element [element ...]',
    desc: 'Append to a list only if the list exists',
  },
  {
    name: 'SADD',
    group: 'set',
    syntax: 'SADD key member [member ...]',
    desc: 'Add one or more members to a set',
  },
  { name: 'SAVE', group: 'server', syntax: 'SAVE', desc: 'Synchronously save the dataset to disk' },
  {
    name: 'SCAN',
    group: 'generic',
    syntax: 'SCAN cursor [MATCH pattern] [COUNT n] [TYPE t]',
    desc: 'Incrementally iterate the keyspace',
  },
  { name: 'SCARD', group: 'set', syntax: 'SCARD key', desc: 'Get the number of members in a set' },
  {
    name: 'SCRIPT',
    group: 'script',
    syntax: 'SCRIPT [LOAD|EXISTS|FLUSH ...]',
    desc: 'Inspect and manipulate the Lua script cache',
  },
  { name: 'SDIFF', group: 'set', syntax: 'SDIFF key [key ...]', desc: 'Subtract multiple sets' },
  {
    name: 'SELECT',
    group: 'connection',
    syntax: 'SELECT index',
    desc: 'Change the selected database for the connection',
  },
  {
    name: 'SET',
    group: 'string',
    syntax: 'SET key value [EX|PX] [NX|XX] [KEEPTTL]',
    desc: 'Set the string value of a key with options',
  },
  {
    name: 'SETBIT',
    group: 'bitmap',
    syntax: 'SETBIT key offset value',
    desc: 'Set or clear the bit at an offset in a string',
  },
  {
    name: 'SETEX',
    group: 'string',
    syntax: 'SETEX key seconds value',
    desc: 'Set a key with an expiry in seconds',
  },
  {
    name: 'SETNX',
    group: 'string',
    syntax: 'SETNX key value',
    desc: 'Set a key only if it does not exist',
  },
  {
    name: 'SETRANGE',
    group: 'string',
    syntax: 'SETRANGE key offset value',
    desc: 'Overwrite part of a string starting at an offset',
  },
  {
    name: 'SHUTDOWN',
    group: 'server',
    syntax: 'SHUTDOWN [NOSAVE|SAVE]',
    desc: 'Stop the server and optionally save data',
  },
  { name: 'SINTER', group: 'set', syntax: 'SINTER key [key ...]', desc: 'Intersect multiple sets' },
  {
    name: 'SISMEMBER',
    group: 'set',
    syntax: 'SISMEMBER key member',
    desc: 'Determine whether a value is a member of a set',
  },
  {
    name: 'SLOWLOG',
    group: 'server',
    syntax: 'SLOWLOG [GET|LEN|RESET]',
    desc: 'Inspect the slow query log',
  },
  { name: 'SMEMBERS', group: 'set', syntax: 'SMEMBERS key', desc: 'Get all the members in a set' },
  {
    name: 'SMISMEMBER',
    group: 'set',
    syntax: 'SMISMEMBER key member [member ...]',
    desc: 'Get the membership status of multiple set members',
  },
  {
    name: 'SMOVE',
    group: 'set',
    syntax: 'SMOVE source destination member',
    desc: 'Move a member from one set to another',
  },
  {
    name: 'SORT',
    group: 'generic',
    syntax: 'SORT key [BY|LIMIT|GET ...]',
    desc: 'Sort the elements of a list, set, or sorted set',
  },
  {
    name: 'SPOP',
    group: 'set',
    syntax: 'SPOP key [count]',
    desc: 'Remove and return one or multiple random members from a set',
  },
  {
    name: 'SRANDMEMBER',
    group: 'set',
    syntax: 'SRANDMEMBER key [count]',
    desc: 'Get one or multiple random members from a set',
  },
  {
    name: 'SREM',
    group: 'set',
    syntax: 'SREM key member [member ...]',
    desc: 'Remove one or more members from a set',
  },
  {
    name: 'SSCAN',
    group: 'set',
    syntax: 'SSCAN key cursor [MATCH pattern] [COUNT n]',
    desc: 'Incrementally iterate over a set',
  },
  {
    name: 'STRLEN',
    group: 'string',
    syntax: 'STRLEN key',
    desc: 'Get the length of the value stored in a key',
  },
  {
    name: 'SUBSCRIBE',
    group: 'pubsub',
    syntax: 'SUBSCRIBE channel [channel ...]',
    desc: 'Listen for messages on one or more channels',
  },
  { name: 'SUNION', group: 'set', syntax: 'SUNION key [key ...]', desc: 'Add multiple sets' },
  { name: 'TIME', group: 'server', syntax: 'TIME', desc: 'Return the current server time' },
  {
    name: 'TOUCH',
    group: 'generic',
    syntax: 'TOUCH key [key ...]',
    desc: 'Mark one or more keys as recently used',
  },
  {
    name: 'TTL',
    group: 'generic',
    syntax: 'TTL key',
    desc: 'Get a key remaining time to live in seconds',
  },
  {
    name: 'TYPE',
    group: 'generic',
    syntax: 'TYPE key',
    desc: 'Determine the type stored at a key',
  },
  {
    name: 'UNLINK',
    group: 'generic',
    syntax: 'UNLINK key [key ...]',
    desc: 'Delete keys asynchronously in the background',
  },
  {
    name: 'UNSUBSCRIBE',
    group: 'pubsub',
    syntax: 'UNSUBSCRIBE [channel ...]',
    desc: 'Stop listening for messages on channels',
  },
  { name: 'UNWATCH', group: 'script', syntax: 'UNWATCH', desc: 'Forget all watched keys' },
  {
    name: 'WATCH',
    group: 'script',
    syntax: 'WATCH key [key ...]',
    desc: 'Watch the given keys for a transaction',
  },
  {
    name: 'XACK',
    group: 'stream',
    syntax: 'XACK key group id [id ...]',
    desc: 'Acknowledge one or more messages of a stream consumer group',
  },
  {
    name: 'XADD',
    group: 'stream',
    syntax: 'XADD key [*|id] field value [field value ...]',
    desc: 'Append a message to a stream',
  },
  {
    name: 'XDEL',
    group: 'stream',
    syntax: 'XDEL key id [id ...]',
    desc: 'Delete one or more messages from a stream',
  },
  {
    name: 'XGROUP',
    group: 'stream',
    syntax: 'XGROUP [CREATE|SETID|DESTROY ...]',
    desc: 'Manage consumer groups of a stream',
  },
  {
    name: 'XINFO',
    group: 'stream',
    syntax: 'XINFO [STREAM|GROUPS|CONSUMERS]',
    desc: 'Inspect streams, groups and consumers',
  },
  {
    name: 'XLEN',
    group: 'stream',
    syntax: 'XLEN key',
    desc: 'Get the number of entries in a stream',
  },
  {
    name: 'XPENDING',
    group: 'stream',
    syntax: 'XPENDING key group [[IDLE] start end count]',
    desc: 'Inspect pending entries for a consumer group',
  },
  {
    name: 'XRANGE',
    group: 'stream',
    syntax: 'XRANGE key start end [COUNT n]',
    desc: 'Return a range of entries in a stream by ID',
  },
  {
    name: 'XREAD',
    group: 'stream',
    syntax: 'XREAD [COUNT|BLOCK] STREAMS key [key ...] id [...]',
    desc: 'Read entries from one or more streams',
  },
  {
    name: 'XREADGROUP',
    group: 'stream',
    syntax: 'XREADGROUP GROUP g c [COUNT|BLOCK] STREAMS key id',
    desc: 'Read entries from a stream as a consumer group',
  },
  {
    name: 'XREVRANGE',
    group: 'stream',
    syntax: 'XREVRANGE key end start [COUNT n]',
    desc: 'Return stream entries in reverse ID order',
  },
  {
    name: 'XTRIM',
    group: 'stream',
    syntax: 'XTRIM key MAXLEN [~] count',
    desc: 'Trim a stream to a given length',
  },
  {
    name: 'ZADD',
    group: 'zset',
    syntax: 'ZADD key [NX|XX] [GT|LT] [CH] score member [...]',
    desc: 'Add one or more members to a sorted set',
  },
  {
    name: 'ZCARD',
    group: 'zset',
    syntax: 'ZCARD key',
    desc: 'Get the number of members in a sorted set',
  },
  {
    name: 'ZCOUNT',
    group: 'zset',
    syntax: 'ZCOUNT key min max',
    desc: 'Count members in a sorted set within a score range',
  },
  {
    name: 'ZINCRBY',
    group: 'zset',
    syntax: 'ZINCRBY key increment member',
    desc: 'Increment the score of a member in a sorted set',
  },
  {
    name: 'ZINTER',
    group: 'zset',
    syntax: 'ZINTER numkeys key [key ...] [WEIGHTS|AGGREGATE]',
    desc: 'Intersect multiple sorted sets',
  },
  {
    name: 'ZLEXCOUNT',
    group: 'zset',
    syntax: 'ZLEXCOUNT key min max',
    desc: 'Count members in a sorted set within a lexicographical range',
  },
  {
    name: 'ZPOPMAX',
    group: 'zset',
    syntax: 'ZPOPMAX key [count]',
    desc: 'Remove and return members with the highest scores',
  },
  {
    name: 'ZPOPMIN',
    group: 'zset',
    syntax: 'ZPOPMIN key [count]',
    desc: 'Remove and return members with the lowest scores',
  },
  {
    name: 'ZRANGE',
    group: 'zset',
    syntax: 'ZRANGE key start stop [WITHSCORES]',
    desc: 'Get members in a sorted set by index',
  },
  {
    name: 'ZRANGEBYSCORE',
    group: 'zset',
    syntax: 'ZRANGEBYSCORE key min max [WITHSCORES]',
    desc: 'Get members in a sorted set within a score range',
  },
  {
    name: 'ZRANK',
    group: 'zset',
    syntax: 'ZRANK key member',
    desc: 'Get the index of a member in a sorted set',
  },
  {
    name: 'ZREM',
    group: 'zset',
    syntax: 'ZREM key member [member ...]',
    desc: 'Remove one or more members from a sorted set',
  },
  {
    name: 'ZREMRANGEBYRANK',
    group: 'zset',
    syntax: 'ZREMRANGEBYRANK key start stop',
    desc: 'Remove members in a sorted set within a rank range',
  },
  {
    name: 'ZREMRANGEBYSCORE',
    group: 'zset',
    syntax: 'ZREMRANGEBYSCORE key min max',
    desc: 'Remove members in a sorted set within a score range',
  },
  {
    name: 'ZREVRANGE',
    group: 'zset',
    syntax: 'ZREVRANGE key start stop [WITHSCORES]',
    desc: 'Get members in reverse index order',
  },
  {
    name: 'ZREVRANK',
    group: 'zset',
    syntax: 'ZREVRANK key member',
    desc: 'Get the reversed index of a member in a sorted set',
  },
  {
    name: 'ZSCAN',
    group: 'zset',
    syntax: 'ZSCAN key cursor [MATCH pattern] [COUNT n]',
    desc: 'Incrementally iterate over a sorted set',
  },
  {
    name: 'ZSCORE',
    group: 'zset',
    syntax: 'ZSCORE key member',
    desc: 'Get the score of a member in a sorted set',
  },
  {
    name: 'ZUNION',
    group: 'zset',
    syntax: 'ZUNION numkeys key [key ...] [WEIGHTS|AGGREGATE]',
    desc: 'Add multiple sorted sets',
  },
];
