import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const mongodbMeta = {
    label: 'MongoDB',
    shortLabel: 'Mb',
    iconBg: 'bg-success',
    iconColor: 'text-success',
    defaultPort: 27017,
    defaultHost: '127.0.0.1',
    defaultUser: '',
    quoteChar: '',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    popularityOrder: 5,
    supportsSQL: false,
    category: 'document',
    connectionView: 'document',
    sqlDialect: 'mongodb',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    clipboardSchemes: ['mongodb', 'mongodb+srv'],
    supportsExplain: false,
    hasMultiDatabase: true,
    structureEditor: {
      enabled: false,
      columnTypes: [],
      defaultColumnType: '',
      fields: {},
      indexMethods: [],
    },
  } satisfies DatabaseTypeMeta;

