import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

const postgresqlStructureEditor = {
  columnTypes: [
    { value: 'integer', label: 'integer' },
    { value: 'bigint', label: 'bigint' },
    { value: 'smallint', label: 'smallint' },
    { value: 'serial', label: 'serial' },
    { value: 'bigserial', label: 'bigserial' },
    { value: 'numeric', label: 'numeric' },
    { value: 'real', label: 'real' },
    { value: 'double precision', label: 'double precision' },
    { value: 'boolean', label: 'boolean' },
    { value: 'varchar(255)', label: 'varchar(255)' },
    { value: 'varchar(50)', label: 'varchar(50)' },
    { value: 'varchar(100)', label: 'varchar(100)' },
    { value: 'text', label: 'text' },
    { value: 'char(1)', label: 'char(1)' },
    { value: 'date', label: 'date' },
    { value: 'time', label: 'time' },
    { value: 'timestamp', label: 'timestamp' },
    { value: 'timestamptz', label: 'timestamptz' },
    { value: 'uuid', label: 'uuid' },
    { value: 'json', label: 'json' },
    { value: 'jsonb', label: 'jsonb' },
    { value: 'bytea', label: 'bytea' },
    { value: 'text[]', label: 'text[]' },
    { value: 'integer[]', label: 'integer[]' },
    { value: 'inet', label: 'inet' },
    { value: 'cidr', label: 'cidr' },
    { value: 'money', label: 'money' },
  ],
  defaultColumnType: 'varchar(255)',
  fields: { comment: true },
  indexMethods: ['btree', 'hash', 'gist', 'gin', 'spgist', 'brin'],
} satisfies NonNullable<DatabaseTypeMeta['structureEditor']>;

export const postgresqlMeta = {
    label: 'PostgreSQL',
    shortLabel: 'Pg',
    iconBg: 'bg-blue-600',
    iconColor: 'text-blue-400',
    defaultPort: 5432,
    defaultHost: '127.0.0.1',
    defaultUser: 'postgres',
    quoteChar: '"',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: true,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'postgresql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
    namespaceEnsure: 'postgresql',
    structureEditor: postgresqlStructureEditor,
  } satisfies DatabaseTypeMeta;

export const questdbMeta = {
    label: 'QuestDB',
    shortLabel: 'Qd',
    iconBg: 'bg-rose-700',
    iconColor: 'text-rose-400',
    defaultPort: 8812,
    defaultHost: '127.0.0.1',
    defaultUser: 'admin',
    quoteChar: '"',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: false,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'postgresql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
    structureEditor: postgresqlStructureEditor,
  } satisfies DatabaseTypeMeta;

export const cloudberryMeta = {
    label: 'Cloudberry',
    shortLabel: 'Cb',
    iconBg: 'bg-teal-700',
    iconColor: 'text-teal-400',
    defaultPort: 5432,
    defaultHost: '127.0.0.1',
    defaultUser: 'postgres',
    quoteChar: '"',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'postgresql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
    structureEditor: postgresqlStructureEditor,
  } satisfies DatabaseTypeMeta;

