export {
  SQL_STATEMENT_START_KEYWORDS,
  buildStatementRangesFromTokens,
  buildStatementRanges,
  getStatementContent,
  getValidStatementRanges,
  findStatementAtCursor,
  getStatementTextAtCursor,
  getCachedStatementIndex,
  setCachedStatementIndex,
  clearStatementIndexCache,
  updateStatementRangesIncremental,
  createStatementIndexState,
  updateStatementIndexState,
  statementIndexField,
  type StatementIndexState,
} from '@datazen/extension-points';
