import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const sqlserverMeta = {
  label: 'SQL Server',
  shortLabel: 'Ss',
  iconBg: 'bg-danger',
  iconColor: 'text-danger',
  defaultPort: 1433,
  defaultHost: '127.0.0.1',
  defaultUser: 'sa',
  quoteChar: '"',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'sqlserver',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['sqlserver', 'mssql'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  supportsCreateDatabase: true,
  supportsCreateSchema: true,
  supportsCreateUser: true,
  structureEditor: {
    columnTypes: [
      { value: 'int', label: 'int' },
      { value: 'bigint', label: 'bigint' },
      { value: 'smallint', label: 'smallint' },
      { value: 'tinyint', label: 'tinyint' },
      { value: 'bit', label: 'bit' },
      { value: 'decimal(18,2)', label: 'decimal(18,2)' },
      { value: 'decimal(10,2)', label: 'decimal(10,2)' },
      { value: 'money', label: 'money' },
      { value: 'float', label: 'float' },
      { value: 'real', label: 'real' },
      { value: 'date', label: 'date' },
      { value: 'time', label: 'time' },
      { value: 'datetime', label: 'datetime' },
      { value: 'datetime2', label: 'datetime2' },
      { value: 'smalldatetime', label: 'smalldatetime' },
      { value: 'uniqueidentifier', label: 'uniqueidentifier' },
      { value: 'char(10)', label: 'char(10)' },
      { value: 'varchar(255)', label: 'varchar(255)' },
      { value: 'varchar(50)', label: 'varchar(50)' },
      { value: 'varchar(100)', label: 'varchar(100)' },
      { value: 'varchar(max)', label: 'varchar(max)' },
      { value: 'nchar(10)', label: 'nchar(10)' },
      { value: 'nvarchar(255)', label: 'nvarchar(255)' },
      { value: 'nvarchar(50)', label: 'nvarchar(50)' },
      { value: 'nvarchar(100)', label: 'nvarchar(100)' },
      { value: 'nvarchar(max)', label: 'nvarchar(max)' },
      { value: 'text', label: 'text' },
      { value: 'ntext', label: 'ntext' },
      { value: 'binary(16)', label: 'binary(16)' },
      { value: 'varbinary(256)', label: 'varbinary(256)' },
      { value: 'varbinary(max)', label: 'varbinary(max)' },
      { value: 'xml', label: 'xml' },
    ],
    defaultColumnType: 'nvarchar(255)',
    fields: {},
    indexMethods: [],
  },
} satisfies DatabaseTypeMeta;
