import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const clickhouseMeta = {
  label: 'ClickHouse',
  shortLabel: 'Ch',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 8123,
  defaultHost: '127.0.0.1',
  defaultUser: 'default',
  quoteChar: '"',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'clickhouse',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['clickhouse'],
  supportsExplain: true,
  hasMultiDatabase: true,
  structureEditor: {
    columnTypes: [
      { value: 'UInt8', label: 'UInt8' },
      { value: 'UInt16', label: 'UInt16' },
      { value: 'UInt32', label: 'UInt32' },
      { value: 'UInt64', label: 'UInt64' },
      { value: 'Int8', label: 'Int8' },
      { value: 'Int16', label: 'Int16' },
      { value: 'Int32', label: 'Int32' },
      { value: 'Int64', label: 'Int64' },
      { value: 'Float32', label: 'Float32' },
      { value: 'Float64', label: 'Float64' },
      { value: 'String', label: 'String' },
      { value: 'FixedString(16)', label: 'FixedString(16)' },
      { value: 'UUID', label: 'UUID' },
      { value: 'Date', label: 'Date' },
      { value: 'DateTime', label: 'DateTime' },
      { value: 'DateTime64(3)', label: 'DateTime64(3)' },
      { value: 'Bool', label: 'Bool' },
      { value: 'Nullable(UInt64)', label: 'Nullable(UInt64)' },
      { value: 'Array(String)', label: 'Array(String)' },
    ],
    defaultColumnType: 'String',
    fields: {},
    indexMethods: ['minmax', 'set', 'bloom_filter', 'ngrambf_v1', 'tokenbf_v1'],
  },
} satisfies DatabaseTypeMeta;
