import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const rqliteMeta = {
  label: 'RQLite',
  shortLabel: 'Rq',
  iconBg: 'bg-accent',
  iconColor: 'text-accent',
  defaultPort: 4001,
  defaultHost: '127.0.0.1',
  defaultUser: '',
  quoteChar: '"',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  popularityOrder: 16,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'sqlite',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['rqlite'],
  supportsExplain: true,
  supportedObjectKinds: ['trigger'],
  structureEditor: {
    columnTypes: [
      { value: 'INTEGER', label: 'INTEGER' },
      { value: 'INT', label: 'INT' },
      { value: 'BIGINT', label: 'BIGINT' },
      { value: 'REAL', label: 'REAL' },
      { value: 'TEXT', label: 'TEXT' },
      { value: 'BLOB', label: 'BLOB' },
      { value: 'NUMERIC', label: 'NUMERIC' },
      { value: 'BOOLEAN', label: 'BOOLEAN' },
      { value: 'VARCHAR(255)', label: 'VARCHAR(255)' },
      { value: 'VARCHAR(50)', label: 'VARCHAR(50)' },
      { value: 'CHAR(1)', label: 'CHAR(1)' },
      { value: 'DATE', label: 'DATE' },
      { value: 'DATETIME', label: 'DATETIME' },
    ],
    defaultColumnType: 'TEXT',
    fields: {},
    indexMethods: ['btree'],
  },
} satisfies DatabaseTypeMeta;
