import { useCallback, useMemo, useState } from 'react';
import { Check, Copy } from 'lucide-react';
import { useI18n } from '../../hooks/useI18n';
import { getDbLabel } from '../../lib/databaseTypes';
import type { DatabaseType } from '../../types';
import { SQL_TOKEN_CLASS, tokenizeSql } from './sqlHighlight';

export interface SqlPreviewProps {
  /** Generated SQL, already pretty-printed. Empty string renders the empty state. */
  sql: string;
  /** Active driver, used for the dialect badge. */
  databaseType?: string;
  /** Overrides the default empty-state hint. */
  emptyHint?: string;
}

/**
 * Read-only preview of the SQL generated by the visual builder.
 *
 * Read-only is deliberate: the builder is the single source of truth for this
 * text, so edits belong in the SQL editor after OK (see PRD §6.3).
 *
 * Highlighting is done by tokenizing the text ourselves and emitting one span
 * per token — no editor instance, no dependency, and the concatenated spans
 * reproduce the generated SQL byte for byte (E2E reads it back via textContent).
 */
export function SqlPreview({ sql, databaseType, emptyHint }: SqlPreviewProps) {
  const { t } = useI18n();
  const [copied, setCopied] = useState(false);

  const tokens = useMemo(() => (sql ? tokenizeSql(sql) : []), [sql]);

  const handleCopy = useCallback(() => {
    if (!sql) return;
    void navigator.clipboard.writeText(sql).then(() => {
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    });
  }, [sql]);

  const dialect = databaseType ? getDbLabel(databaseType as DatabaseType) : null;

  if (!sql) {
    return (
      <div className="flex flex-1 flex-col p-3" data-testid="qb-sql-preview-empty">
        <p className="text-xs text-fg-muted">
          {emptyHint ?? t('query.visualBuilder.previewEmpty')}
        </p>
      </div>
    );
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col gap-1.5 p-3">
      <div className="flex shrink-0 items-center gap-2">
        <span className="text-[11px] font-medium text-fg-secondary">
          {t('query.visualBuilder.preview')}
        </span>
        {dialect && (
          <span
            className="rounded bg-surface-inset px-1.5 py-0.5 text-[10px] text-fg-muted"
            data-testid="qb-preview-dialect"
          >
            {t('query.visualBuilder.dialect')}: {dialect}
          </span>
        )}
        <div className="flex-1" />
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1 rounded px-2 py-0.5 text-[11px] text-fg-muted transition-colors hover:bg-surface-raised hover:text-fg"
          data-testid="qb-copy-sql"
        >
          {copied ? <Check className="h-3 w-3 text-success" /> : <Copy className="h-3 w-3" />}
          {copied ? t('query.visualBuilder.copied') : t('query.visualBuilder.copySql')}
        </button>
      </div>
      <pre
        className="min-h-0 flex-1 select-all overflow-auto rounded-lg border border-edge bg-surface-alt p-3 font-mono text-[12px] leading-relaxed text-fg"
        data-testid="qb-sql-preview"
      >
        <code>
          {tokens.map((token, index) => (
            <span key={index} className={SQL_TOKEN_CLASS[token.kind]}>
              {token.text}
            </span>
          ))}
        </code>
      </pre>
    </div>
  );
}
