-- Durable PostgreSQL Schema Tree fixtures for manual testing.
-- Install with install-manual-schema-tree.sh. All objects live in their own
-- schema so the E2E teardown never touches this fixture database.

CREATE SCHEMA IF NOT EXISTS manual_schema_tree;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'manual_schema_tree'
      AND t.typname = 'manual_schema_tree_state'
  ) THEN
    CREATE TYPE manual_schema_tree.manual_schema_tree_state AS ENUM ('active', 'archived');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'manual_schema_tree'
      AND t.typname = 'manual_schema_tree_code'
  ) THEN
    CREATE DOMAIN manual_schema_tree.manual_schema_tree_code AS text
      CHECK (VALUE ~ '^[A-Z0-9-]{1,24}$');
  END IF;
END $$;

CREATE SEQUENCE IF NOT EXISTS manual_schema_tree.manual_schema_tree_group_id_seq
  START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS manual_schema_tree.manual_schema_tree_groups (
  group_id integer NOT NULL DEFAULT nextval('manual_schema_tree.manual_schema_tree_group_id_seq'),
  group_name text NOT NULL UNIQUE,
  CONSTRAINT manual_schema_tree_groups_pk PRIMARY KEY (group_id)
);

ALTER SEQUENCE manual_schema_tree.manual_schema_tree_group_id_seq
  OWNED BY manual_schema_tree.manual_schema_tree_groups.group_id;

CREATE TABLE IF NOT EXISTS manual_schema_tree.manual_schema_tree_entries (
  entry_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL,
  code manual_schema_tree.manual_schema_tree_code NOT NULL UNIQUE,
  title text NOT NULL,
  state manual_schema_tree.manual_schema_tree_state NOT NULL DEFAULT 'active',
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT manual_schema_tree_entries_group_fk
    FOREIGN KEY (group_id)
    REFERENCES manual_schema_tree.manual_schema_tree_groups (group_id)
);

CREATE INDEX IF NOT EXISTS manual_schema_tree_entries_state_group_idx
  ON manual_schema_tree.manual_schema_tree_entries (state, group_id);

CREATE OR REPLACE VIEW manual_schema_tree.manual_schema_tree_active_entries AS
SELECT e.entry_id, g.group_name, e.code, e.title, e.state, e.updated_at
FROM manual_schema_tree.manual_schema_tree_entries AS e
JOIN manual_schema_tree.manual_schema_tree_groups AS g USING (group_id)
WHERE e.state = 'active';

CREATE OR REPLACE FUNCTION manual_schema_tree.manual_schema_tree_normalize_code(input_code text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT upper(btrim(input_code));
$$;

CREATE OR REPLACE PROCEDURE manual_schema_tree.manual_schema_tree_archive_entry(p_entry_id integer)
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE manual_schema_tree.manual_schema_tree_entries
  SET state = 'archived', updated_at = now()
  WHERE entry_id = p_entry_id;
END;
$$;

CREATE OR REPLACE FUNCTION manual_schema_tree.manual_schema_tree_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS manual_schema_tree_entries_touch_updated_at
  ON manual_schema_tree.manual_schema_tree_entries;
CREATE TRIGGER manual_schema_tree_entries_touch_updated_at
  BEFORE UPDATE ON manual_schema_tree.manual_schema_tree_entries
  FOR EACH ROW
  EXECUTE FUNCTION manual_schema_tree.manual_schema_tree_touch_updated_at();

INSERT INTO manual_schema_tree.manual_schema_tree_groups (group_id, group_name)
VALUES (1001, 'Manual fixtures'), (1002, 'Manual examples')
ON CONFLICT (group_id) DO NOTHING;

DO $$
DECLARE
  last_group_id bigint;
  has_groups boolean;
BEGIN
  SELECT COALESCE(MAX(group_id), 1), COUNT(*) > 0
  INTO last_group_id, has_groups
  FROM manual_schema_tree.manual_schema_tree_groups;
  PERFORM setval('manual_schema_tree.manual_schema_tree_group_id_seq', last_group_id, has_groups);
END $$;

INSERT INTO manual_schema_tree.manual_schema_tree_entries
  (entry_id, group_id, code, title, state)
VALUES
  (2001, 1001, 'MANUAL-001', 'Active manual fixture row', 'active'),
  (2002, 1002, 'MANUAL-002', 'Archived manual fixture row', 'archived')
ON CONFLICT (entry_id) DO NOTHING;

DO $$
DECLARE
  last_entry_id bigint;
  has_entries boolean;
BEGIN
  SELECT COALESCE(MAX(entry_id), 1), COUNT(*) > 0
  INTO last_entry_id, has_entries
  FROM manual_schema_tree.manual_schema_tree_entries;
  PERFORM setval(
    pg_get_serial_sequence('manual_schema_tree.manual_schema_tree_entries', 'entry_id'),
    last_entry_id,
    has_entries
  );
END $$;
