import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const duckdbMeta = {
  label: 'DuckDB',
  shortLabel: 'Dk',
  iconBg: 'bg-accent',
  iconColor: 'text-accent',
  defaultPort: 0,
  defaultHost: '',
  defaultUser: '',
  quoteChar: '"',
  connectionMode: 'file',
  supportsSSH: false,
  supportsSSL: false,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  popularityOrder: 12,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'duckdb',
  databaseFieldType: 'path',
  connectionForm: 'file',
  clipboardSchemes: ['duckdb'],
  supportsExplain: true,
  supportedObjectKinds: ['trigger', 'sequence'],
  structureEditor: {
    columnTypes: [
      { value: 'INTEGER', label: 'INTEGER' },
      { value: 'BIGINT', label: 'BIGINT' },
      { value: 'HUGEINT', label: 'HUGEINT' },
      { value: 'SMALLINT', label: 'SMALLINT' },
      { value: 'TINYINT', label: 'TINYINT' },
      { value: 'REAL', label: 'REAL' },
      { value: 'DOUBLE', label: 'DOUBLE' },
      { value: 'DECIMAL(18,3)', label: 'DECIMAL(18,3)' },
      { value: 'VARCHAR', label: 'VARCHAR' },
      { value: 'CHAR', label: 'CHAR' },
      { value: 'BLOB', label: 'BLOB' },
      { value: 'BOOLEAN', label: 'BOOLEAN' },
      { value: 'DATE', label: 'DATE' },
      { value: 'TIME', label: 'TIME' },
      { value: 'TIMESTAMP', label: 'TIMESTAMP' },
      { value: 'TIMESTAMP WITH TIME ZONE', label: 'TIMESTAMPTZ' },
      { value: 'UUID', label: 'UUID' },
      { value: 'JSON', label: 'JSON' },
    ],
    defaultColumnType: 'VARCHAR',
    fields: {},
    indexMethods: ['btree', 'art'],
  },
} satisfies DatabaseTypeMeta;
