import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const mysqlMeta = {
    label: 'MySQL',
    shortLabel: 'My',
    iconBg: 'bg-orange-500',
    iconColor: 'text-orange-400',
    defaultPort: 3306,
    defaultHost: '127.0.0.1',
    defaultUser: 'root',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: true,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

export const mariadbMeta = {
    label: 'MariaDB',
    shortLabel: 'Ma',
    iconBg: 'bg-sky-600',
    iconColor: 'text-amber-500',
    defaultPort: 3306,
    defaultHost: '127.0.0.1',
    defaultUser: 'root',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: true,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

export const dorisMeta = {
    label: 'Doris',
    shortLabel: 'Do',
    iconBg: 'bg-cyan-700',
    iconColor: 'text-cyan-400',
    defaultPort: 9030,
    defaultHost: '127.0.0.1',
    defaultUser: 'root',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

export const starrocksMeta = {
    label: 'StarRocks',
    shortLabel: 'Sr',
    iconBg: 'bg-indigo-700',
    iconColor: 'text-indigo-400',
    defaultPort: 9030,
    defaultHost: '127.0.0.1',
    defaultUser: 'root',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

export const manticoreMeta = {
    label: 'ManticoreSearch',
    shortLabel: 'Mc',
    iconBg: 'bg-lime-700',
    iconColor: 'text-lime-400',
    defaultPort: 9306,
    defaultHost: '127.0.0.1',
    defaultUser: '',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: false,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

export const obOracleMeta = {
    label: 'OceanBase (Oracle)',
    shortLabel: 'Ob',
    iconBg: 'bg-slate-600',
    iconColor: 'text-slate-400',
    defaultPort: 2881,
    defaultHost: '127.0.0.1',
    defaultUser: 'root',
    quoteChar: '`',
    connectionMode: 'server',
    supportsSSH: true,
    supportsSSL: true,
    supportsBackup: false,
    supportsTables: true,
    isKeyValue: false,
    supportsSQL: true,
    category: 'sql',
    connectionView: 'sql',
    sqlDialect: 'mysql',
    databaseFieldType: 'name',
    connectionForm: 'standard',
    supportsExplain: true,
    hasMultiDatabase: true,
  } satisfies DatabaseTypeMeta;

