import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

const mysqlStructureEditor = {
  columnTypes: [
    { value: 'TINYINT', label: 'TINYINT' },
    { value: 'SMALLINT', label: 'SMALLINT' },
    { value: 'MEDIUMINT', label: 'MEDIUMINT' },
    { value: 'INT', label: 'INT' },
    { value: 'BIGINT', label: 'BIGINT' },
    { value: 'TINYINT UNSIGNED', label: 'TINYINT UNSIGNED' },
    { value: 'SMALLINT UNSIGNED', label: 'SMALLINT UNSIGNED' },
    { value: 'MEDIUMINT UNSIGNED', label: 'MEDIUMINT UNSIGNED' },
    { value: 'INT UNSIGNED', label: 'INT UNSIGNED' },
    { value: 'BIGINT UNSIGNED', label: 'BIGINT UNSIGNED' },
    { value: 'DECIMAL(10,2)', label: 'DECIMAL(10,2)' },
    { value: 'FLOAT', label: 'FLOAT' },
    { value: 'DOUBLE', label: 'DOUBLE' },
    { value: 'BOOLEAN', label: 'BOOLEAN' },
    { value: 'VARCHAR(255)', label: 'VARCHAR(255)' },
    { value: 'VARCHAR(50)', label: 'VARCHAR(50)' },
    { value: 'VARCHAR(100)', label: 'VARCHAR(100)' },
    { value: 'CHAR(1)', label: 'CHAR(1)' },
    { value: 'TEXT', label: 'TEXT' },
    { value: 'MEDIUMTEXT', label: 'MEDIUMTEXT' },
    { value: 'LONGTEXT', label: 'LONGTEXT' },
    { value: 'DATE', label: 'DATE' },
    { value: 'TIME', label: 'TIME' },
    { value: 'DATETIME', label: 'DATETIME' },
    { value: 'TIMESTAMP', label: 'TIMESTAMP' },
    { value: 'YEAR', label: 'YEAR' },
    { value: 'JSON', label: 'JSON' },
    { value: 'BLOB', label: 'BLOB' },
    { value: 'MEDIUMBLOB', label: 'MEDIUMBLOB' },
    { value: 'LONGBLOB', label: 'LONGBLOB' },
  ],
  defaultColumnType: 'VARCHAR(255)',
  fields: {
    comment: true,
    charset: true,
    collation: true,
    unsigned: true,
    length: true,
  },
  indexMethods: ['BTREE', 'HASH'],
} satisfies NonNullable<DatabaseTypeMeta['structureEditor']>;

const mysqlStructureEditorSpread = { structureEditor: mysqlStructureEditor } as const;

export const mysqlMeta = {
  label: 'MySQL',
  shortLabel: 'My',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 3306,
  defaultHost: '127.0.0.1',
  defaultUser: 'root',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['mysql'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;

export const mariadbMeta = {
  label: 'MariaDB',
  shortLabel: 'Ma',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 3306,
  defaultHost: '127.0.0.1',
  defaultUser: 'root',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['mariadb'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;

export const dorisMeta = {
  label: 'Doris',
  shortLabel: 'Do',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 9030,
  defaultHost: '127.0.0.1',
  defaultUser: 'root',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['doris'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;

export const starrocksMeta = {
  label: 'StarRocks',
  shortLabel: 'Sr',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 9030,
  defaultHost: '127.0.0.1',
  defaultUser: 'root',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['starrocks'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;

export const manticoreMeta = {
  label: 'ManticoreSearch',
  shortLabel: 'Mc',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 9306,
  defaultHost: '127.0.0.1',
  defaultUser: '',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: false,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['manticore'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;

export const obOracleMeta = {
  label: 'OceanBase (Oracle)',
  shortLabel: 'Ob',
  iconBg: 'bg-warning',
  iconColor: 'text-warning',
  defaultPort: 2881,
  defaultHost: '127.0.0.1',
  defaultUser: 'root',
  quoteChar: '`',
  connectionMode: 'server',
  supportsSSH: true,
  supportsSSL: true,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'mysql',
  databaseFieldType: 'name',
  connectionForm: 'standard',
  clipboardSchemes: ['oceanbase'],
  supportsExplain: true,
  hasMultiDatabase: true,
  supportedObjectKinds: ['function', 'procedure', 'trigger'],
  ...mysqlStructureEditorSpread,
} satisfies DatabaseTypeMeta;
