#!/usr/bin/env node
/**
 * resolve-pro.mjs
 *
 * Pre-build script that resolves whether to build DataZen Community or DataZen Pro.
 * Controlled via:
 *   --edition=community      (default: pure open-source fallback)
 *   --edition=pro            (injects SQL Editor Pro extension)
 *   --pro                    (alias for --edition=pro)
 *   --community              (alias for --edition=community)
 *   --restore                (restores clean Community state)
 *   --pro-path=<path>        (local path to @datazen/extension-sql-editor-pro)
 *   --pro-git=<url>          (git clone url for @datazen/extension-sql-editor-pro)
 *   --codegen-only           (only write generated-pro.ts, skip git operations)
 *
 * Environment variables:
 *   DATAZEN_EDITION="pro" | "community"
 *   DATAZEN_PRO_PATH="/path/to/datazen-extension-sql-editor-pro"
 *   DATAZEN_PRO_GIT="https://github.com/flyxl/datazen-extension-sql-editor-pro.git"
 *
 * Generates:
 *   src/plugins/generated-pro.ts (gitignored)
 */

import { existsSync, writeFileSync, mkdirSync, cpSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(__dirname, '..');
export const PRO_EXT_DIR = resolve(ROOT, 'packages/pro-extensions');
export const DEFAULT_PRO_DEST = resolve(PRO_EXT_DIR, 'sql-editor-pro');
export const DEFAULT_PRO_GIT = 'https://github.com/flyxl/datazen-extension-sql-editor-pro.git';
export const GENERATED_PRO_TS = resolve(ROOT, 'src/plugins/generated-pro.ts');

export function parseArgs(argv = process.argv.slice(2)) {
  let edition = process.env.DATAZEN_EDITION || 'community';
  let proPath = process.env.DATAZEN_PRO_PATH || null;
  let proGit = process.env.DATAZEN_PRO_GIT || DEFAULT_PRO_GIT;
  let restore = false;
  let codegenOnly = false;

  for (const arg of argv) {
    if (arg === '--pro' || arg === '--edition=pro') {
      edition = 'pro';
    } else if (arg === '--community' || arg === '--edition=community') {
      edition = 'community';
    } else if (arg === '--restore') {
      restore = true;
      edition = 'community';
    } else if (arg === '--codegen-only') {
      codegenOnly = true;
    } else if (arg.startsWith('--pro-path=')) {
      proPath = arg.slice('--pro-path='.length);
    } else if (arg.startsWith('--pro-git=')) {
      proGit = arg.slice('--pro-git='.length);
    }
  }

  return { edition, proPath, proGit, restore, codegenOnly };
}

export function writeCommunityCodegen(dest = GENERATED_PRO_TS) {
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: community
 */
export const DATAZEN_EDITION = 'community' as const;

export function initProExtensions(): void {
  // Community edition: no pro extensions registered.
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Community edition');
}

export function writeProCodegen(dest = GENERATED_PRO_TS) {
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: pro
 */
import { activate as activateSqlEditorPro } from '@datazen/extension-sql-editor-pro';

export const DATAZEN_EDITION = 'pro' as const;

export function initProExtensions(): void {
  activateSqlEditorPro();
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Pro edition (SQL Editor Pro active)');
}

export function ensureProCheckout({ proPath, proGit, codegenOnly } = {}) {
  if (proPath && existsSync(proPath)) {
    console.log(`[resolve-pro] using explicitly provided pro path: ${proPath}`);
    return proPath;
  }

  // Check if already in packages/pro-extensions/sql-editor-pro
  if (existsSync(DEFAULT_PRO_DEST)) {
    console.log(`[resolve-pro] using existing checkout at ${DEFAULT_PRO_DEST}`);
    return DEFAULT_PRO_DEST;
  }

  // Check local fallback (/tmp/datazen-extension-sql-editor-pro)
  const tmpFallback = '/tmp/datazen-extension-sql-editor-pro';
  if (existsSync(tmpFallback)) {
    console.log(`[resolve-pro] copying local checkout from ${tmpFallback}`);
    mkdirSync(PRO_EXT_DIR, { recursive: true });
    try {
      cpSync(tmpFallback, DEFAULT_PRO_DEST, { recursive: true });
    } catch {
      // In case cpSync fails, clone or proceed
    }
    if (existsSync(DEFAULT_PRO_DEST)) {
      return DEFAULT_PRO_DEST;
    }
    return tmpFallback;
  }

  if (codegenOnly) {
    console.warn('[resolve-pro] codegen-only specified, skipping git clone');
    return null;
  }

  // Clone from git
  console.log(`[resolve-pro] cloning Pro extension from ${proGit} ...`);
  mkdirSync(PRO_EXT_DIR, { recursive: true });
  try {
    execSync(`git clone ${proGit} ${DEFAULT_PRO_DEST}`, { stdio: 'inherit' });
    console.log(`[resolve-pro] cloned successfully into ${DEFAULT_PRO_DEST}`);
    return DEFAULT_PRO_DEST;
  } catch (err) {
    console.error(`[resolve-pro] failed to clone Pro extension from ${proGit}:`, err.message);
    throw err;
  }
}

export function resolvePro(opts = {}) {
  const parsed = parseArgs();
  const edition = opts.edition ?? parsed.edition ?? 'community';
  const proPath = opts.proPath ?? parsed.proPath;
  const proGit = opts.proGit ?? parsed.proGit;
  const restore = opts.restore ?? parsed.restore;
  const codegenOnly = opts.codegenOnly ?? parsed.codegenOnly;

  if (restore || edition === 'community') {
    writeCommunityCodegen();
    return { edition: 'community', active: false };
  }

  if (edition === 'pro') {
    const targetPath = ensureProCheckout({ proPath, proGit, codegenOnly });
    writeProCodegen();
    return { edition: 'pro', active: true, path: targetPath };
  }

  throw new Error(`[resolve-pro] unknown edition: "${edition}" (expected "community" or "pro")`);
}

// CLI entry point
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  try {
    resolvePro();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
