#!/usr/bin/env node
/**
 * resolve-pro.mjs
 *
 * Pre-build script that resolves whether to build DataZen Community or DataZen Pro.
 * Controlled via:
 *   --edition=community      (default: pure open-source fallback)
 *   --edition=pro            (injects SQL Editor Pro extension)
 *   --pro                    (alias for --edition=pro)
 *   --community              (alias for --edition=community)
 *   --restore                (restores clean Community state)
 *   --pro-path=<path>        (local path to @datazen/extension-sql-editor-pro)
 *   --pro-git=<url>          (git clone url for @datazen/extension-sql-editor-pro)
 *   --pro-ref=<ref>          (pin the cloned extension to a commit/tag)
 *   --codegen-only           (only write generated-pro.ts, skip git operations)
 *
 * Environment variables:
 *   DATAZEN_EDITION="pro" | "community"
 *   DATAZEN_PRO_PATH="/path/to/datazen-extension-sql-editor-pro"
 *   DATAZEN_PRO_GIT="https://github.com/flyxl/datazen-extension-sql-editor-pro.git"
 *   DATAZEN_PRO_REF="<commit sha or tag>"
 *
 * A freshly cloned extension is pinned to `pro-extension.lock.json` (or the
 * --pro-ref / DATAZEN_PRO_REF override) so that building a host tag reproduces
 * the exact extension revision that tag shipped. An existing local checkout is
 * left alone, so day-to-day development keeps using working-tree code.
 *
 * When a signed tree is already staged under `builtin-ep/sql-editor-pro` and
 * nobody asked for a specific source, that tree is used as-is — this is how CI
 * builds the extension once and shares it with every release variant.
 *
 * Generates:
 *   src/extensions/generated-pro.ts (gitignored)
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, cpSync, rmSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { packEp, DEFAULT_BUILTIN_EP_ROOT } from './pack-ep.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(__dirname, '..');
export const PRO_EXT_DIR = resolve(ROOT, 'packages/pro-extensions');
export const DEFAULT_PRO_DEST = resolve(PRO_EXT_DIR, 'sql-editor-pro');
export const DEFAULT_PRO_GIT = 'https://github.com/flyxl/datazen-extension-sql-editor-pro.git';
export const GENERATED_PRO_TS = resolve(ROOT, 'src/extensions/generated-pro.ts');
export const PRO_LOCK_FILE = resolve(ROOT, 'pro-extension.lock.json');

/**
 * Read the pinned Pro extension revision.
 *
 * The lock file is what makes a host tag reproducible: without it the clone
 * below takes the Pro repo's default-branch HEAD, so re-packaging an old tag
 * would silently bundle whatever the extension looked like at build time.
 * Returns `{ git, ref }` with `null` for anything the lock file omits.
 */
export function readProLock(lockFile = PRO_LOCK_FILE) {
  if (!existsSync(lockFile)) return { git: null, ref: null };
  try {
    const lock = JSON.parse(readFileSync(lockFile, 'utf-8'));
    return {
      git: typeof lock.git === 'string' && lock.git ? lock.git : null,
      ref: typeof lock.ref === 'string' && lock.ref ? lock.ref : null,
    };
  } catch (err) {
    throw new Error(`[resolve-pro] failed to parse ${lockFile}: ${err.message}`);
  }
}

export function parseArgs(argv = process.argv.slice(2)) {
  let explicitEdition = null;
  let edition = process.env.DATAZEN_EDITION || 'community';
  let proPath = process.env.DATAZEN_PRO_PATH || null;
  // Left null when neither the environment nor the CLI picked a URL, so callers
  // can tell "a git source was requested" from "no source specified" — the
  // "already staged" short-circuit depends on that distinction.
  let proGit = process.env.DATAZEN_PRO_GIT || null;
  let proRef = process.env.DATAZEN_PRO_REF || null;
  let restore = false;
  let codegenOnly = false;
  let prebuiltUrl = process.env.DATAZEN_PRO_PREBUILT_URL || null;

  for (const arg of argv) {
    if (arg === '--pro' || arg === '--edition=pro') {
      edition = 'pro';
      explicitEdition = 'pro';
    } else if (arg === '--community' || arg === '--edition=community') {
      edition = 'community';
      explicitEdition = 'community';
    } else if (arg === '--restore') {
      restore = true;
      edition = 'community';
      explicitEdition = 'community';
    } else if (arg === '--codegen-only') {
      codegenOnly = true;
    } else if (arg.startsWith('--pro-path=')) {
      proPath = arg.slice('--pro-path='.length);
    } else if (arg.startsWith('--pro-git=')) {
      proGit = arg.slice('--pro-git='.length);
    } else if (arg.startsWith('--pro-ref=')) {
      proRef = arg.slice('--pro-ref='.length);
    } else if (arg.startsWith('--pro-prebuilt-url=')) {
      prebuiltUrl = arg.slice('--pro-prebuilt-url='.length);
    }
  }

  return { edition, explicitEdition, proPath, proGit, proRef, restore, codegenOnly, prebuiltUrl };
}

export function writeCommunityCodegen(dest = GENERATED_PRO_TS) {
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: community
 */
export const DATAZEN_EDITION = 'community' as const;

export function initProExtensions(): void {
  // Community edition: no pro extensions registered.
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Community edition');
}

export function writeProCodegen(dest = GENERATED_PRO_TS, { proPath = DEFAULT_PRO_DEST } = {}) {
  const devEntry = resolve(proPath, 'src/index.ts').replace(/\\/g, '/');
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: pro (track B: staged builtin-ep bundle loaded at runtime).
 *
 * The SQL Editor Pro extension ships as a STAGED asset
 * (\`src-tauri/resources/builtin-ep/sql-editor-pro/\`, packed by pack-ep.mjs:
 * \`manifest.json\` + rewritten \`dist/index.esm.js\` + \`signature.sig\`) and is
 * loaded through \`hostExtensionLoader.loadFromUrl\` AFTER signature
 * verification. The rewrite step (pack-ep) redirects every bare import to the
 * host shared-singleton table (\`globalThis.__DATAZEN_HOST__\`), so the
 * blob-loaded bundle shares \`@codemirror/*\`, the extension-points registry,
 * React and the i18n bridge with the host instead of forking its own copies.
 */
import { hostExtensionLoader, verifyExtensionPackage } from '@datazen/extension-points';

export const DATAZEN_EDITION = 'pro' as const;

const SQL_EDITOR_PRO_ID = 'sql-editor-pro';
const PRO_DEV_ENTRY = '${devEntry}';

/**
 * Resolve the staged Pro extension: manifest + signature + entry bundle.
 * DEV serves the extension source straight from disk (Vite resolves bare
 * imports there). PROD fetches the staged asset through the Tauri asset
 * protocol and imports from a blob URL — dynamic \`import()\` cannot handle
 * Tauri's custom \`asset://\` (macOS) / \`http://asset.localhost\` (Windows)
 * schemes in all WebView engines, but blob URLs work universally.
 */
async function resolveBuiltinEpPackage(): Promise<{
  manifest: { id: string; version: string; main?: string; engines?: Record<string, unknown> };
  manifestContent: string;
  bundleContent: string;
  signatureContent: string | null;
  entryUrl: string;
} | null> {
  if (!('__TAURI_INTERNALS__' in globalThis)) {
    return null;
  }
  try {
    if (import.meta.env.DEV) {
      const entryUrl = '/@fs' + PRO_DEV_ENTRY;
      const resp = await fetch(entryUrl);
      if (!resp.ok) {
        throw new Error(\`dev entry fetch failed: \${resp.status} \${resp.statusText}\`);
      }
      const bundleContent = await resp.text();
      return {
        manifest: { id: SQL_EDITOR_PRO_ID, version: 'dev' },
        manifestContent: '{}',
        bundleContent,
        // Local dev source: trusted as a local-link, no signature expected.
        signatureContent: null,
        entryUrl,
      };
    }
    const { resourceDir, join } = await import('@tauri-apps/api/path');
    const { convertFileSrc } = await import('@tauri-apps/api/core');
    const base = await resourceDir();
    const extDir = async (...segs: string[]) => join(base, 'builtin-ep', SQL_EDITOR_PRO_ID, ...segs);
    const fetchText = async (rel: string) => {
      const assetUrl = convertFileSrc(await extDir(...rel.split('/')));
      const resp = await fetch(assetUrl);
      if (!resp.ok) {
        throw new Error(\`fetch \${rel} failed: \${resp.status} \${resp.statusText}\`);
      }
      return resp.text();
    };
    const manifestContent = await fetchText('manifest.json');
    const bundleContent = await fetchText('dist/index.esm.js');
    let signatureContent: string | null = null;
    try {
      signatureContent = await fetchText('signature.sig');
    } catch {
      signatureContent = null;
    }
    const entryPath = await extDir('dist', 'index.esm.js');
    const assetUrl = convertFileSrc(entryPath);
    const resp = await fetch(assetUrl);
    if (!resp.ok) {
      throw new Error(\`fetch failed: \${resp.status} \${resp.statusText}\`);
    }
    const blob = await resp.blob();
    const entryUrl = URL.createObjectURL(new Blob([blob], { type: 'application/javascript' }));
    return {
      manifest: JSON.parse(manifestContent),
      manifestContent,
      bundleContent,
      signatureContent,
      entryUrl,
    };
  } catch (err) {
    console.warn('[pro] failed to resolve builtin SQL Editor Pro package:', err);
    return null;
  }
}

export function initProExtensions(): void {
  void (async () => {
    const pkg = await resolveBuiltinEpPackage();
    if (!pkg) {
      console.warn('[pro] builtin SQL Editor Pro extension not found; running community fallback');
      return;
    }
    try {
      // Track B loads from disk (staged asset or dev source), which is trusted
      // like a local-link: engine compatibility is still enforced, signatures
      // are verified when present (PROD), dev sources skip the gate.
      const verification = await verifyExtensionPackage({
        manifest: pkg.manifest,
        files: {
          manifestContent: pkg.manifestContent,
          bundleContent: pkg.bundleContent,
          signatureContent: pkg.signatureContent,
        },
        sourceKind: pkg.signatureContent ? 'dzx' : 'local-link',
      });
      if (!verification.ok) {
        console.error(
          \`[pro] refusing to load SQL Editor Pro (\${verification.code}): \${verification.reason}\`,
        );
        return;
      }
      await hostExtensionLoader.loadFromUrl(SQL_EDITOR_PRO_ID, pkg.entryUrl);
      console.log(\`[pro] SQL Editor Pro activated from builtin-ep (trust: \${verification.trustSource})\`);
    } catch (err) {
      console.error('[pro] failed to activate SQL Editor Pro from builtin-ep:', err);
    }
  })();
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Pro edition (track B builtin-ep loader active)');
}

/**
 * Remove a staged extension tree from the builtin-ep resource root.
 *
 * `stageDir` overrides the landing path (callers that must not touch the real
 * staging tree — e.g. tests — redirect it to a tmp directory). When it is
 * omitted the resolved path is byte-for-byte the historical default
 * `builtin-ep/<extension>`.
 */
export function clearBuiltinEpStaging(extension = 'sql-editor-pro', { stageDir } = {}) {
  const target = stageDir ? resolve(stageDir) : resolve(DEFAULT_BUILTIN_EP_ROOT, extension);
  if (existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
    console.log(`[resolve-pro] removed staged builtin-ep at ${target}`);
  }
}

/**
 * Download a prebuilt pro extension tarball and extract it directly to the
 * builtin-ep staging directory.  The tarball is expected to contain the
 * already-staged package tree (manifest.json, dist/, signature.sig, etc.)
 * — no build or signing step is needed after extraction.
 *
 * @param {{ prebuiltUrl: string, extension?: string, stageDir?: string }} opts
 */
export function downloadPrebuiltEp({ prebuiltUrl, extension = 'sql-editor-pro', stageDir } = {}) {
  const target = stageDir ? resolve(stageDir) : resolve(DEFAULT_BUILTIN_EP_ROOT, extension);
  mkdirSync(target, { recursive: true });

  const tmpDir = resolve(ROOT, '.pro-prebuilt-download');
  mkdirSync(tmpDir, { recursive: true });
  const tarball = resolve(tmpDir, 'prebuilt.tar.gz');

  console.log(`[resolve-pro] downloading prebuilt EP from ${prebuiltUrl} ...`);
  try {
    // Try gh release download first (works with deploy keys for private repos)
    // Fall back to curl/wget for public URLs
    const isGithubUrl = prebuiltUrl.includes('github.com');
    if (isGithubUrl && !prebuiltUrl.includes('/releases/download/')) {
      // It's a tag-based URL — construct the asset name
      // Expect format: pro-{version} tag name
      throw new Error('tag-based download not supported, use full asset URL');
    }

    try {
      execSync(
        `curl -fsSL -o "${tarball}" "${prebuiltUrl}"`,
        { stdio: 'pipe' }
      );
    } catch {
      // curl failed — try wget
      execSync(
        `wget -q -O "${tarball}" "${prebuiltUrl}"`,
        { stdio: 'pipe' }
      );
    }

    // Extract to target dir
    execSync(
      `tar -xzf "${tarball}" -C "${target}"`,
      { stdio: 'pipe' }
    );

    // Verify required files
    const required = ['manifest.json', 'dist/index.esm.js'];
    for (const f of required) {
      if (!existsSync(resolve(target, f))) {
        throw new Error(`prebuilt tarball missing required file: ${f}`);
      }
    }

    console.log(`[resolve-pro] prebuilt EP extracted to ${target}`);
    return target;
  } catch (err) {
    console.error(`[resolve-pro] prebuilt download failed: ${err.message}`);
    throw err;
  } finally {
    // Cleanup temp files
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

export function stageProExtension({
  extensionDir,
  skipBuild = false,
  mode = 'stage',
  log = console.log,
  stageDir,
  outDir,
} = {}) {
  return packEp({
    extensionDir,
    mode,
    skipBuild,
    log,
    // `undefined` keeps pack-ep's own defaults (builtin-ep/<extension>, artifacts/).
    stageDir,
    outDir,
  });
}

/**
 * Detach `dir` at `ref` and return the resulting commit sha.
 *
 * A full clone already contains the object, so this works for tags and shas
 * alike. Throws if the ref cannot be resolved — a pinned build must fail loudly
 * rather than quietly fall back to the default branch.
 */
export function pinProCheckout(dir, ref, { log = console.log } = {}) {
  if (!ref) return null;
  execSync(`git -C ${dir} checkout --detach ${ref}`, { stdio: 'inherit' });
  const head = execSync(`git -C ${dir} rev-parse HEAD`, { encoding: 'utf-8' }).trim();
  log(`[resolve-pro] Pro extension pinned at ${head}`);
  return head;
}

/**
 * Locate (or clone) the Pro extension checkout.
 *
 * `proDest` and `tmpFallbackDir` are path overrides for callers that must not
 * write into the real tree (tests redirect both into a tmp sandbox). Omitting
 * them keeps the historical paths exactly as they were.
 */
export function ensureProCheckout({
  proPath,
  proGit,
  proRef,
  codegenOnly,
  proDest = DEFAULT_PRO_DEST,
  tmpFallbackDir = '/tmp/datazen-extension-sql-editor-pro',
} = {}) {
  if (proPath && existsSync(proPath)) {
    console.log(`[resolve-pro] using explicitly provided pro path: ${proPath}`);
    return proPath;
  }

  // Check if already in packages/pro-extensions/sql-editor-pro
  if (existsSync(proDest)) {
    console.log(`[resolve-pro] using existing checkout at ${proDest}`);
    return proDest;
  }

  // Check local fallback (/tmp/datazen-extension-sql-editor-pro)
  const tmpFallback = tmpFallbackDir;
  if (existsSync(tmpFallback)) {
    console.log(`[resolve-pro] copying local checkout from ${tmpFallback}`);
    mkdirSync(PRO_EXT_DIR, { recursive: true });
    try {
      cpSync(tmpFallback, proDest, { recursive: true });
    } catch {
      // In case cpSync fails, clone or proceed
    }
    if (existsSync(proDest)) {
      return proDest;
    }
    return tmpFallback;
  }

  if (codegenOnly) {
    console.warn('[resolve-pro] codegen-only specified, skipping git clone');
    return null;
  }

  // Clone from git
  console.log(`[resolve-pro] cloning Pro extension from ${proGit} ...`);
  mkdirSync(PRO_EXT_DIR, { recursive: true });
  try {
    execSync(`git clone ${proGit} ${proDest}`, { stdio: 'inherit' });
    console.log(`[resolve-pro] cloned successfully into ${proDest}`);

    if (proRef) {
      // Detach so the pinned revision is not mistaken for a branch to commit on.
      pinProCheckout(proDest, proRef);
    } else {
      console.warn(
        '[resolve-pro] WARNING: no Pro extension ref pinned ' +
          '(pro-extension.lock.json / --pro-ref / DATAZEN_PRO_REF). ' +
          'Building the default-branch HEAD — this release is NOT reproducible.',
      );
    }

    return proDest;
  } catch (err) {
    console.error(`[resolve-pro] failed to clone Pro extension from ${proGit}:`, err.message);
    throw err;
  }
}

/**
 * Resolve the build edition, writing the codegen and staging the Pro bundle.
 *
 * Every landing spot is overridable for callers that must not touch the real
 * tree (tests use tmp paths for all three):
 *   - `opts.codegenPath` → target of `generated-pro.ts` (default `GENERATED_PRO_TS`)
 *   - `opts.stageDir`    → staging directory of the packed bundle
 *                          (default `builtin-ep/sql-editor-pro`)
 *   - `opts.outDir`      → pack-ep work/archive root (default `artifacts/`)
 * Omitting them reproduces the historical defaults exactly.
 */
export function resolvePro(opts = {}) {
  const parsed = parseArgs();
  const explicitEdition =
    opts.edition ??
    parsed.explicitEdition ??
    (process.env.DATAZEN_EDITION ? parsed.edition : null);
  const edition = explicitEdition ?? 'community';
  const proPath = opts.proPath ?? parsed.proPath;
  const restore = opts.restore ?? parsed.restore;
  const codegenOnly = opts.codegenOnly ?? parsed.codegenOnly;
  const prebuiltUrl = opts.prebuiltUrl ?? parsed.prebuiltUrl;
  const codegenPath = opts.codegenPath ? resolve(opts.codegenPath) : GENERATED_PRO_TS;
  const stageDir = opts.stageDir ? resolve(opts.stageDir) : null;
  const outDir = opts.outDir ? resolve(opts.outDir) : undefined;

  // Pin precedence: explicit option > CLI/env > lock file. `null` disables the
  // pin, which is what local development wants.
  const lock = readProLock();
  const proRef = opts.proRef !== undefined ? opts.proRef : (parsed.proRef ?? lock.ref);
  // A caller only "requested" a git source via --pro-git / DATAZEN_PRO_GIT. When
  // nobody did, the lock file names the repo the pinned ref lives in, and a tree
  // already staged under builtin-ep (e.g. a CI artifact) is used as-is.
  const requestedGit = opts.proGit ?? parsed.proGit ?? null;
  const proGitExplicit = requestedGit !== null;
  const proGit = requestedGit ?? lock.git ?? DEFAULT_PRO_GIT;

  // If codegenOnly is requested without an explicit edition, and generated-pro.ts already exists, preserve it!
  if (codegenOnly && !explicitEdition && !restore && existsSync(codegenPath)) {
    console.log('[resolve-pro] generated-pro.ts already exists; preserving existing edition');
    return { edition: 'preserved', active: true };
  }

  if (restore || edition === 'community') {
    clearBuiltinEpStaging('sql-editor-pro', { stageDir });
    writeCommunityCodegen(codegenPath);
    return { edition: 'community', active: false };
  }

  if (edition === 'pro') {
    // Fast path: prebuilt tarball (downloaded in CI or via --pro-prebuilt-url)
    const builtinEpDir = stageDir ?? resolve(DEFAULT_BUILTIN_EP_ROOT, 'sql-editor-pro');
    const hasPrebuiltFiles =
      existsSync(resolve(builtinEpDir, 'manifest.json')) &&
      existsSync(resolve(builtinEpDir, 'dist/index.esm.js'));

    if (prebuiltUrl && !codegenOnly) {
      if (hasPrebuiltFiles) {
        console.log('[resolve-pro] prebuilt EP already staged, skipping download');
        writeProCodegen(codegenPath, { proPath: proPath || builtinEpDir });
        return { edition: 'pro', active: true, path: builtinEpDir, prebuilt: true };
      }
      try {
        const targetPath = downloadPrebuiltEp({ prebuiltUrl, stageDir });
        writeProCodegen(codegenPath, { proPath: targetPath || proPath || DEFAULT_PRO_DEST });
        return { edition: 'pro', active: true, path: targetPath, prebuilt: true };
      } catch (err) {
        console.warn(`[resolve-pro] prebuilt download failed, falling back to git clone: ${err.message}`);
      }
    }

    // If a signed tree is already staged (CI builds the extension once and
    // shares it with every variant as an artifact), just write the codegen.
    if (hasPrebuiltFiles && !proPath && !proGitExplicit && !codegenOnly) {
      console.log('[resolve-pro] pro extension already staged in builtin-ep, writing codegen');
      writeProCodegen(codegenPath, { proPath: proPath || builtinEpDir });
      return { edition: 'pro', active: true, path: builtinEpDir, prebuilt: true };
    }

    // Standard path: clone/build from source, then stage the rewritten +
    // signed bundle as a Tauri resource (track B: loaded at runtime).
    const targetPath = ensureProCheckout({ proPath, proGit, proRef, codegenOnly });
    writeProCodegen(codegenPath, { proPath: targetPath || proPath || DEFAULT_PRO_DEST });
    if (!codegenOnly && targetPath) {
      stageProExtension({ extensionDir: targetPath, mode: 'stage', stageDir, outDir });
    }
    return { edition: 'pro', active: true, path: targetPath };
  }

  throw new Error(`[resolve-pro] unknown edition: "${edition}" (expected "community" or "pro")`);
}

// CLI entry point
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  try {
    resolvePro();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
