#!/usr/bin/env node
/**
 * resolve-pro.mjs
 *
 * Pre-build script that resolves whether to build DataZen Community or DataZen Pro.
 * Controlled via:
 *   --edition=community      (default: pure open-source fallback)
 *   --edition=pro            (injects SQL Editor Pro extension)
 *   --pro                    (alias for --edition=pro)
 *   --community              (alias for --edition=community)
 *   --restore                (restores clean Community state)
 *   --pro-path=<path>        (local path to @datazen/extension-sql-editor-pro)
 *   --pro-git=<url>          (git clone url for @datazen/extension-sql-editor-pro)
 *   --codegen-only           (only write generated-pro.ts, skip git operations)
 *
 * Environment variables:
 *   DATAZEN_EDITION="pro" | "community"
 *   DATAZEN_PRO_PATH="/path/to/datazen-extension-sql-editor-pro"
 *   DATAZEN_PRO_GIT="https://github.com/flyxl/datazen-extension-sql-editor-pro.git"
 *
 * Generates:
 *   src/extensions/generated-pro.ts (gitignored)
 */

import { existsSync, writeFileSync, mkdirSync, cpSync, rmSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { packEp, DEFAULT_BUILTIN_EP_ROOT } from './pack-ep.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(__dirname, '..');
export const PRO_EXT_DIR = resolve(ROOT, 'packages/pro-extensions');
export const DEFAULT_PRO_DEST = resolve(PRO_EXT_DIR, 'sql-editor-pro');
export const DEFAULT_PRO_GIT = 'https://github.com/flyxl/datazen-extension-sql-editor-pro.git';
export const GENERATED_PRO_TS = resolve(ROOT, 'src/extensions/generated-pro.ts');

export function parseArgs(argv = process.argv.slice(2)) {
  let explicitEdition = null;
  let edition = process.env.DATAZEN_EDITION || 'community';
  let proPath = process.env.DATAZEN_PRO_PATH || null;
  let proGit = process.env.DATAZEN_PRO_GIT || DEFAULT_PRO_GIT;
  let restore = false;
  let codegenOnly = false;
  let prebuiltUrl = process.env.DATAZEN_PRO_PREBUILT_URL || null;

  for (const arg of argv) {
    if (arg === '--pro' || arg === '--edition=pro') {
      edition = 'pro';
      explicitEdition = 'pro';
    } else if (arg === '--community' || arg === '--edition=community') {
      edition = 'community';
      explicitEdition = 'community';
    } else if (arg === '--restore') {
      restore = true;
      edition = 'community';
      explicitEdition = 'community';
    } else if (arg === '--codegen-only') {
      codegenOnly = true;
    } else if (arg.startsWith('--pro-path=')) {
      proPath = arg.slice('--pro-path='.length);
    } else if (arg.startsWith('--pro-git=')) {
      proGit = arg.slice('--pro-git='.length);
    } else if (arg.startsWith('--pro-prebuilt-url=')) {
      prebuiltUrl = arg.slice('--pro-prebuilt-url='.length);
    }
  }

  return { edition, explicitEdition, proPath, proGit, restore, codegenOnly, prebuiltUrl };
}

export function writeCommunityCodegen(dest = GENERATED_PRO_TS) {
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: community
 */
export const DATAZEN_EDITION = 'community' as const;

export function initProExtensions(): void {
  // Community edition: no pro extensions registered.
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Community edition');
}

export function writeProCodegen(dest = GENERATED_PRO_TS, { proPath = DEFAULT_PRO_DEST } = {}) {
  const devEntry = resolve(proPath, 'src/index.ts').replace(/\\/g, '/');
  const content = `/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: pro
 */
import { hostExtensionLoader } from '@datazen/extension-points';

export const DATAZEN_EDITION = 'pro' as const;

const SQL_EDITOR_PRO_ID = 'sql-editor-pro';
const PRO_DEV_ENTRY = '${devEntry}';

async function resolveBuiltinEpEntryUrl(): Promise<string | null> {
  if (!('__TAURI_INTERNALS__' in globalThis)) {
    return null;
  }
  try {
    if (import.meta.env.DEV) {
      return '/@fs' + PRO_DEV_ENTRY;
    }
    const { resourceDir, join } = await import('@tauri-apps/api/path');
    const { convertFileSrc } = await import('@tauri-apps/api/core');
    const base = await resourceDir();
    const entryPath = await join(base, 'builtin-ep', SQL_EDITOR_PRO_ID, 'dist', 'index.esm.js');
    return convertFileSrc(entryPath);
  } catch (err) {
    console.warn('[pro] failed to resolve builtin SQL Editor Pro entry:', err);
    return null;
  }
}

export function initProExtensions(): void {
  void (async () => {
    const entryUrl = await resolveBuiltinEpEntryUrl();
    if (!entryUrl) {
      console.warn('[pro] builtin SQL Editor Pro extension not found; running community fallback');
      return;
    }
    try {
      await hostExtensionLoader.loadFromUrl(SQL_EDITOR_PRO_ID, entryUrl);
    } catch (err) {
      console.error('[pro] failed to activate SQL Editor Pro from builtin-ep:', err);
    }
  })();
}
`;
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content, 'utf-8');
  console.log('[resolve-pro] generated-pro.ts written for Pro edition (builtin-ep loader active)');
}

export function clearBuiltinEpStaging(extension = 'sql-editor-pro') {
  const target = resolve(DEFAULT_BUILTIN_EP_ROOT, extension);
  if (existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
    console.log(`[resolve-pro] removed staged builtin-ep at ${target}`);
  }
}

/**
 * Download a prebuilt pro extension tarball and extract it directly to the
 * builtin-ep staging directory.  The tarball is expected to contain the
 * already-staged package tree (manifest.json, dist/, signature.sig, etc.)
 * — no build or signing step is needed after extraction.
 *
 * @param {{ prebuiltUrl: string, extension?: string }} opts
 */
export function downloadPrebuiltEp({ prebuiltUrl, extension = 'sql-editor-pro' } = {}) {
  const target = resolve(DEFAULT_BUILTIN_EP_ROOT, extension);
  mkdirSync(target, { recursive: true });

  const tmpDir = resolve(ROOT, '.pro-prebuilt-download');
  mkdirSync(tmpDir, { recursive: true });
  const tarball = resolve(tmpDir, 'prebuilt.tar.gz');

  console.log(`[resolve-pro] downloading prebuilt EP from ${prebuiltUrl} ...`);
  try {
    // Try gh release download first (works with deploy keys for private repos)
    // Fall back to curl/wget for public URLs
    const isGithubUrl = prebuiltUrl.includes('github.com');
    if (isGithubUrl && !prebuiltUrl.includes('/releases/download/')) {
      // It's a tag-based URL — construct the asset name
      // Expect format: pro-{version} tag name
      throw new Error('tag-based download not supported, use full asset URL');
    }

    try {
      execSync(
        `curl -fsSL -o "${tarball}" "${prebuiltUrl}"`,
        { stdio: 'pipe' }
      );
    } catch {
      // curl failed — try wget
      execSync(
        `wget -q -O "${tarball}" "${prebuiltUrl}"`,
        { stdio: 'pipe' }
      );
    }

    // Extract to target dir
    execSync(
      `tar -xzf "${tarball}" -C "${target}"`,
      { stdio: 'pipe' }
    );

    // Verify required files
    const required = ['manifest.json', 'dist/index.esm.js'];
    for (const f of required) {
      if (!existsSync(resolve(target, f))) {
        throw new Error(`prebuilt tarball missing required file: ${f}`);
      }
    }

    console.log(`[resolve-pro] prebuilt EP extracted to ${target}`);
    return target;
  } catch (err) {
    console.error(`[resolve-pro] prebuilt download failed: ${err.message}`);
    throw err;
  } finally {
    // Cleanup temp files
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

export function stageProExtension({
  extensionDir,
  skipBuild = false,
  mode = 'stage',
  log = console.log,
} = {}) {
  return packEp({
    extensionDir,
    mode,
    skipBuild,
    log,
  });
}

export function ensureProCheckout({ proPath, proGit, codegenOnly } = {}) {
  if (proPath && existsSync(proPath)) {
    console.log(`[resolve-pro] using explicitly provided pro path: ${proPath}`);
    return proPath;
  }

  // Check if already in packages/pro-extensions/sql-editor-pro
  if (existsSync(DEFAULT_PRO_DEST)) {
    console.log(`[resolve-pro] using existing checkout at ${DEFAULT_PRO_DEST}`);
    return DEFAULT_PRO_DEST;
  }

  // Check local fallback (/tmp/datazen-extension-sql-editor-pro)
  const tmpFallback = '/tmp/datazen-extension-sql-editor-pro';
  if (existsSync(tmpFallback)) {
    console.log(`[resolve-pro] copying local checkout from ${tmpFallback}`);
    mkdirSync(PRO_EXT_DIR, { recursive: true });
    try {
      cpSync(tmpFallback, DEFAULT_PRO_DEST, { recursive: true });
    } catch {
      // In case cpSync fails, clone or proceed
    }
    if (existsSync(DEFAULT_PRO_DEST)) {
      return DEFAULT_PRO_DEST;
    }
    return tmpFallback;
  }

  if (codegenOnly) {
    console.warn('[resolve-pro] codegen-only specified, skipping git clone');
    return null;
  }

  // Clone from git
  console.log(`[resolve-pro] cloning Pro extension from ${proGit} ...`);
  mkdirSync(PRO_EXT_DIR, { recursive: true });
  try {
    execSync(`git clone ${proGit} ${DEFAULT_PRO_DEST}`, { stdio: 'inherit' });
    console.log(`[resolve-pro] cloned successfully into ${DEFAULT_PRO_DEST}`);
    return DEFAULT_PRO_DEST;
  } catch (err) {
    console.error(`[resolve-pro] failed to clone Pro extension from ${proGit}:`, err.message);
    throw err;
  }
}

export function resolvePro(opts = {}) {
  const parsed = parseArgs();
  const explicitEdition =
    opts.edition ??
    parsed.explicitEdition ??
    (process.env.DATAZEN_EDITION ? parsed.edition : null);
  const edition = explicitEdition ?? 'community';
  const proPath = opts.proPath ?? parsed.proPath;
  const proGit = opts.proGit ?? parsed.proGit;
  const restore = opts.restore ?? parsed.restore;
  const codegenOnly = opts.codegenOnly ?? parsed.codegenOnly;
  const prebuiltUrl = opts.prebuiltUrl ?? parsed.prebuiltUrl;

  // If codegenOnly is requested without an explicit edition, and generated-pro.ts already exists, preserve it!
  if (codegenOnly && !explicitEdition && !restore && existsSync(GENERATED_PRO_TS)) {
    console.log('[resolve-pro] generated-pro.ts already exists; preserving existing edition');
    return { edition: 'preserved', active: true };
  }

  if (restore || edition === 'community') {
    clearBuiltinEpStaging();
    writeCommunityCodegen();
    return { edition: 'community', active: false };
  }

  if (edition === 'pro') {
    // Fast path: prebuilt tarball (downloaded in CI or via --pro-prebuilt-url)
    const builtinEpDir = resolve(DEFAULT_BUILTIN_EP_ROOT, 'sql-editor-pro');
    const hasPrebuiltFiles =
      existsSync(resolve(builtinEpDir, 'manifest.json')) &&
      existsSync(resolve(builtinEpDir, 'dist/index.esm.js'));

    if (prebuiltUrl && !codegenOnly) {
      if (hasPrebuiltFiles) {
        console.log('[resolve-pro] prebuilt EP already staged, skipping download');
        writeProCodegen(GENERATED_PRO_TS, { proPath: proPath || builtinEpDir });
        return { edition: 'pro', active: true, path: builtinEpDir, prebuilt: true };
      }
      try {
        const targetPath = downloadPrebuiltEp({ prebuiltUrl });
        writeProCodegen(GENERATED_PRO_TS, { proPath: targetPath || proPath || DEFAULT_PRO_DEST });
        return { edition: 'pro', active: true, path: targetPath, prebuilt: true };
      } catch (err) {
        console.warn(`[resolve-pro] prebuilt download failed, falling back to git clone: ${err.message}`);
      }
    }

    // If prebuilt files are already staged (e.g., by CI download step), just codegen
    if (hasPrebuiltFiles && !proPath && !proGit && !codegenOnly) {
      console.log('[resolve-pro] pro extension already staged in builtin-ep, writing codegen');
      writeProCodegen(GENERATED_PRO_TS, { proPath: proPath || builtinEpDir });
      return { edition: 'pro', active: true, path: builtinEpDir, prebuilt: true };
    }

    // Standard path: clone + build from source
    const targetPath = ensureProCheckout({ proPath, proGit, codegenOnly });
    writeProCodegen(GENERATED_PRO_TS, { proPath: targetPath || proPath || DEFAULT_PRO_DEST });
    if (!codegenOnly && targetPath) {
      stageProExtension({ extensionDir: targetPath, mode: 'stage' });
    }
    return { edition: 'pro', active: true, path: targetPath };
  }

  throw new Error(`[resolve-pro] unknown edition: "${edition}" (expected "community" or "pro")`);
}

// CLI entry point
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  try {
    resolvePro();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
