/**
 * AUTO-GENERATED by resolve-pro.mjs — DO NOT EDIT MANUALLY.
 * Edition: community
 */
export const DATAZEN_EDITION = 'community' as const;

export function initProExtensions(): void {
  // Community edition: no pro extensions registered.
}
