/**
 * AUTO-GENERATED by resolve-drivers.mjs — DO NOT EDIT MANUALLY
 *
 * This file registers frontend components and metadata for active plugins.
 * Regenerated every time the build runs with different --drivers args.
 */
import { postgresqlMeta, questdbMeta, cloudberryMeta } from '../../packages/drivers/postgres/ui/meta';
import { mysqlMeta, mariadbMeta, dorisMeta, starrocksMeta, manticoreMeta, obOracleMeta } from '../../packages/drivers/mysql/ui/meta';
import { sqliteMeta } from '../../packages/drivers/sqlite/ui/meta';
import { redisMeta } from '../../packages/drivers/redis/ui/meta';
import { mongodbMeta } from '../../packages/drivers/mongodb/ui/meta';
import { sqlserverMeta } from '../../packages/drivers/sqlserver/ui/meta';
import { clickhouseMeta } from '../../packages/drivers/clickhouse/ui/meta';
import { duckdbMeta } from '../../packages/drivers/duckdb/ui/meta';
import { elasticsearchMeta } from '../../packages/drivers/elasticsearch/ui/meta';
import { rqliteMeta } from '../../packages/drivers/rqlite/ui/meta';
import { tursoMeta } from '../../packages/drivers/turso/ui/meta';
import { influxdbMeta } from '../../packages/drivers/influxdb/ui/meta';
import { victoriametricsMeta } from '../../packages/drivers/victoriametrics/ui/meta';
import { hbaseMeta } from '../../packages/drivers/hbase/ui/meta';
import { vectorMeta } from '../../packages/drivers/vector/ui/meta';
import { kiwiMeta } from '../../.plugins/kiwi/ui/plugin-meta';
import { KiwiConnectionFields } from '../../.plugins/kiwi/ui/KiwiConnectionFields';
import { prestoMeta, trinoMeta } from '../../.plugins/olap/ui/plugin-meta';
import { CatalogConnectionFields } from '../../.plugins/olap/ui/CatalogConnectionFields';
import { trinoDialect } from '../../.plugins/olap/ui/trinoDialect';
import { supersetMeta } from '../../.plugins/superset/ui/plugin-meta';
import { SupersetConnectionFields, supersetValidate } from '../../.plugins/superset/ui/SupersetConnectionFields';
import { SupersetSchemaTree } from '../../.plugins/superset/ui/SupersetSchemaTree';
import driverIcon_postgresql from '../../packages/drivers/postgres/ui/icons/postgresql.svg?url';
import driverIcon_mysql from '../../packages/drivers/mysql/ui/icons/mysql.svg?url';
import driverIcon_mariadb from '../../packages/drivers/mysql/ui/icons/mariadb.svg?url';
import driverIcon_sqlite from '../../packages/drivers/sqlite/ui/icons/sqlite.svg?url';
import driverIcon_redis from '../../packages/drivers/redis/ui/icons/redis.svg?url';
import driverIcon_mongodb from '../../packages/drivers/mongodb/ui/icons/mongodb.svg?url';
import driverIcon_sqlserver from '../../packages/drivers/sqlserver/ui/icons/sqlserver.svg?url';
import driverIcon_clickhouse from '../../packages/drivers/clickhouse/ui/icons/clickhouse.svg?url';
import driverIcon_duckdb from '../../packages/drivers/duckdb/ui/icons/duckdb.svg?url';
import driverIcon_elasticsearch from '../../packages/drivers/elasticsearch/ui/icons/elasticsearch.svg?url';
import driverIcon_rqlite from '../../packages/drivers/rqlite/ui/icons/rqlite.svg?url';
import driverIcon_turso from '../../packages/drivers/turso/ui/icons/turso.svg?url';
import driverIcon_influxdb from '../../packages/drivers/influxdb/ui/icons/influxdb.svg?url';
import driverIcon_victoriametrics from '../../packages/drivers/victoriametrics/ui/icons/victoriametrics.svg?url';
import driverIcon_hbase from '../../packages/drivers/hbase/ui/icons/hbase.svg?url';
import driverIcon_vector from '../../packages/drivers/vector/ui/icons/vector.svg?url';
import { invoke } from '@tauri-apps/api/core';
import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';
import type { SqlDialectStrategy } from '@datazen/plugin-sdk';
import type { PluginFormValidator } from '@datazen/plugin-sdk';
import type { ComponentType } from 'react';

/**
 * Frontend plugin protocol version.
 * Must match the version expected by the main app.
 * Bump when making breaking changes to plugin interfaces.
 */
export const PLUGIN_PROTOCOL_VERSION = 1;

/** Database types contributed by active drivers in this build. */
export type DatabaseType = 'postgresql' | 'questdb' | 'cloudberry' | 'mysql' | 'mariadb' | 'doris' | 'starrocks' | 'manticore' | 'ob_oracle' | 'sqlite' | 'redis' | 'mongodb' | 'sqlserver' | 'clickhouse' | 'duckdb' | 'elasticsearch' | 'rqlite' | 'turso' | 'influxdb' | 'victoriametrics' | 'hbase' | 'vector' | 'kiwi' | 'presto' | 'trino' | 'superset';

/** Driver DB metadata entries (merged into DB_REGISTRY at runtime). */
export const DRIVER_DB_ENTRIES: Record<string, DatabaseTypeMeta> = {
  postgresql: postgresqlMeta,
  questdb: questdbMeta,
  cloudberry: cloudberryMeta,
  mysql: mysqlMeta,
  mariadb: mariadbMeta,
  doris: dorisMeta,
  starrocks: starrocksMeta,
  manticore: manticoreMeta,
  ob_oracle: obOracleMeta,
  sqlite: sqliteMeta,
  redis: redisMeta,
  mongodb: mongodbMeta,
  sqlserver: sqlserverMeta,
  clickhouse: clickhouseMeta,
  duckdb: duckdbMeta,
  elasticsearch: elasticsearchMeta,
  rqlite: rqliteMeta,
  turso: tursoMeta,
  influxdb: influxdbMeta,
  victoriametrics: victoriametricsMeta,
  hbase: hbaseMeta,
  vector: vectorMeta,
  kiwi: kiwiMeta,
  presto: prestoMeta,
  trino: trinoMeta,
  superset: supersetMeta,
};

/** Default driver badge icon URLs keyed by semantic id (`db.<type>`). */
export const DRIVER_ICON_ENTRIES: Record<string, string> = {
  'db.postgresql': driverIcon_postgresql,
  'db.questdb': driverIcon_postgresql,
  'db.cloudberry': driverIcon_postgresql,
  'db.mysql': driverIcon_mysql,
  'db.mariadb': driverIcon_mariadb,
  'db.doris': driverIcon_mysql,
  'db.starrocks': driverIcon_mysql,
  'db.manticore': driverIcon_mysql,
  'db.ob_oracle': driverIcon_mysql,
  'db.sqlite': driverIcon_sqlite,
  'db.redis': driverIcon_redis,
  'db.mongodb': driverIcon_mongodb,
  'db.sqlserver': driverIcon_sqlserver,
  'db.clickhouse': driverIcon_clickhouse,
  'db.duckdb': driverIcon_duckdb,
  'db.elasticsearch': driverIcon_elasticsearch,
  'db.rqlite': driverIcon_rqlite,
  'db.turso': driverIcon_turso,
  'db.influxdb': driverIcon_influxdb,
  'db.victoriametrics': driverIcon_victoriametrics,
  'db.hbase': driverIcon_hbase,
  'db.vector': driverIcon_vector,
};

/** @deprecated Use DatabaseType */
export type PluginDatabaseType = DatabaseType;

/** @deprecated Use DRIVER_DB_ENTRIES */
export const PLUGIN_DB_ENTRIES = DRIVER_DB_ENTRIES;

/** Plugin-provided SQL dialect strategies (merged into DIALECTS). */
export const PLUGIN_SQL_DIALECTS: Record<string, SqlDialectStrategy> = {
  trino: trinoDialect,
};

/** Plugin-provided connection form components. */
interface PluginFormEntry {
  formVariant: string;
  component: ComponentType<any>;
}

const PLUGIN_FORMS: PluginFormEntry[] = [
  { formVariant: 'kiwi', component: KiwiConnectionFields },
  { formVariant: 'catalog', component: CatalogConnectionFields },
  { formVariant: 'superset', component: SupersetConnectionFields },
];

/** Lookup plugin-provided connection form by form variant (e.g. 'kiwi', 'catalog'). */
export function getPluginConnectionForm(formVariant: string): ComponentType<any> | undefined {
  for (const entry of PLUGIN_FORMS) {
    if (entry.formVariant === formVariant) {
      return entry.component;
    }
  }
  return undefined;
}

/** Plugin-provided form validators, keyed by form variant. */
const PLUGIN_VALIDATORS: Record<string, PluginFormValidator> = {
  superset: supersetValidate,
};

/** Lookup plugin-provided form validator by form variant. */
export function getPluginValidator(formVariant: string): PluginFormValidator | undefined {
  return PLUGIN_VALIDATORS[formVariant];
}

// ===== Plugin Schema Trees =====

interface PluginSchemaTreeEntry {
  dbType: string;
  component: ComponentType<any>;
}

const PLUGIN_SCHEMA_TREES: PluginSchemaTreeEntry[] = [
  { dbType: 'superset', component: SupersetSchemaTree },
];

/** Lookup plugin-provided schema tree by database type. */
export function getPluginSchemaTree(dbType: string): ComponentType<any> | undefined {
  for (const entry of PLUGIN_SCHEMA_TREES) {
    if (entry.dbType === dbType) {
      return entry.component;
    }
  }
  return undefined;
}

// ===== Plugin Commands =====

export interface PluginCommandMeta {
  pluginId: string;
  commands: string[];
}

/** Commands registered by active plugins via Tauri Plugin system. */
export const PLUGIN_COMMANDS: PluginCommandMeta[] = [
  { pluginId: 'kiwi', commands: ['login', 'list_instances'] },
];

/** Invoke a plugin-provided Tauri command using plugin:id|command format. */
export async function pluginInvoke<T = unknown>(
  pluginId: string,
  command: string,
  args?: Record<string, unknown>,
): Promise<T> {
  return invoke<T>(`plugin:${pluginId}|${command}`, args ?? {});
}

/** Check whether a specific plugin command is available in this build. */
export function hasPluginCommand(pluginId: string, command: string): boolean {
  return PLUGIN_COMMANDS.some(
    (p) => p.pluginId === pluginId && p.commands.includes(command),
  );
}
