/**
 * AUTO-GENERATED by resolve-plugins.mjs — DO NOT EDIT MANUALLY
 *
 * This file registers frontend components and metadata for active plugins.
 * Regenerated every time the build runs with different --plugins args.
 */
import { kiwiMeta } from '../../.plugins/kiwi/ui/plugin-meta';
import { KiwiConnectionFields } from '../../.plugins/kiwi/ui/KiwiConnectionFields';
import { prestoMeta, trinoMeta } from '../../.plugins/olap/ui/plugin-meta';
import { CatalogConnectionFields } from '../../.plugins/olap/ui/CatalogConnectionFields';
import { trinoDialect } from '../../.plugins/olap/ui/trinoDialect';
import { invoke } from '@tauri-apps/api/core';
import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';
import type { SqlDialectStrategy } from '@datazen/plugin-sdk';
import type { ComponentType } from 'react';

/**
 * Frontend plugin protocol version.
 * Must match the version expected by the main app.
 * Bump when making breaking changes to plugin interfaces.
 */
export const PLUGIN_PROTOCOL_VERSION = 1;

/** Database types contributed by active plugins. */
export type PluginDatabaseType = 'kiwi' | 'presto' | 'trino';

/** Plugin DB metadata entries (merged into DB_REGISTRY at runtime). */
export const PLUGIN_DB_ENTRIES: Record<string, DatabaseTypeMeta> = {
  kiwi: kiwiMeta,
  presto: prestoMeta,
  trino: trinoMeta,
};

/** Plugin-provided SQL dialect strategies (merged into DIALECTS). */
export const PLUGIN_SQL_DIALECTS: Record<string, SqlDialectStrategy> = {
  trino: trinoDialect,
};

/** Plugin-provided connection form components. */
interface PluginFormEntry {
  formVariant: string;
  component: ComponentType<any>;
}

const PLUGIN_FORMS: PluginFormEntry[] = [
  { formVariant: 'kiwi', component: KiwiConnectionFields },
  { formVariant: 'catalog', component: CatalogConnectionFields },
];

/** Lookup plugin-provided connection form by form variant (e.g. 'kiwi', 'catalog'). */
export function getPluginConnectionForm(formVariant: string): ComponentType<any> | undefined {
  for (const entry of PLUGIN_FORMS) {
    if (entry.formVariant === formVariant) {
      return entry.component;
    }
  }
  return undefined;
}

// ===== Plugin Commands =====

export interface PluginCommandMeta {
  pluginId: string;
  commands: string[];
}

/** Commands registered by active plugins via Tauri Plugin system. */
export const PLUGIN_COMMANDS: PluginCommandMeta[] = [
  { pluginId: 'kiwi', commands: ['login', 'list_instances'] },
];

/** Invoke a plugin-provided Tauri command using plugin:id|command format. */
export async function pluginInvoke<T = unknown>(
  pluginId: string,
  command: string,
  args?: Record<string, unknown>,
): Promise<T> {
  return invoke<T>(`plugin:${pluginId}|${command}`, args ?? {});
}

/** Check whether a specific plugin command is available in this build. */
export function hasPluginCommand(pluginId: string, command: string): boolean {
  return PLUGIN_COMMANDS.some(
    (p) => p.pluginId === pluginId && p.commands.includes(command),
  );
}
