// AUTO-GENERATED by resolve-plugins.mjs — DO NOT EDIT MANUALLY
//
// Registers Tauri plugins provided by external driver plugins.
// Each plugin that declares a `tauriPlugin` block in plugins-registry.json
// gets a conditional .plugin() registration here.

use tauri::Runtime;

pub fn register_plugins<R: Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    let builder = builder;

    // No plugins with Tauri commands enabled

    builder
}
