// AUTO-GENERATED by resolve-drivers.mjs — DO NOT EDIT MANUALLY
//
// Ensures plugin crates are linked into the binary (extern crate)
// so that inventory-based driver registration takes effect.
// Also registers Tauri plugins for crates that declare a tauriPlugin block.

use tauri::Runtime;

pub fn register_plugins<R: Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    let builder = builder;

    // No plugins with Tauri commands enabled

    builder
}
