import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const sqliteMeta = {
  label: 'SQLite',
  shortLabel: 'Lt',
  iconBg: 'bg-success',
  iconColor: 'text-success',
  defaultPort: 0,
  defaultHost: '',
  defaultUser: '',
  quoteChar: '"',
  connectionMode: 'file',
  supportsSSH: false,
  supportsSSL: false,
  supportsBackup: true,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'sqlite',
  databaseFieldType: 'path',
  connectionForm: 'file',
  clipboardSchemes: ['sqlite', 'sqlite3'],
  supportsExplain: true,
  supportedObjectKinds: ['trigger'],
  structureEditor: {
    columnTypes: [
      { value: 'INTEGER', label: 'INTEGER' },
      { value: 'INT', label: 'INT' },
      { value: 'BIGINT', label: 'BIGINT' },
      { value: 'REAL', label: 'REAL' },
      { value: 'TEXT', label: 'TEXT' },
      { value: 'BLOB', label: 'BLOB' },
      { value: 'NUMERIC', label: 'NUMERIC' },
      { value: 'BOOLEAN', label: 'BOOLEAN' },
      { value: 'VARCHAR(255)', label: 'VARCHAR(255)' },
      { value: 'VARCHAR(50)', label: 'VARCHAR(50)' },
      { value: 'CHAR(1)', label: 'CHAR(1)' },
      { value: 'DATE', label: 'DATE' },
      { value: 'DATETIME', label: 'DATETIME' },
    ],
    defaultColumnType: 'TEXT',
    fields: {},
    indexMethods: ['btree'],
  },
} satisfies DatabaseTypeMeta;
