/** Common Redis commands for console completion (uppercase). */
export const REDIS_COMMANDS: readonly string[] = [
  'ACL',
  'APPEND',
  'AUTH',
  'BGREWRITEAOF',
  'BGSAVE',
  'BITCOUNT',
  'BITFIELD',
  'CLIENT',
  'CLUSTER',
  'CONFIG',
  'COPY',
  'DBSIZE',
  'DECR',
  'DECRBY',
  'DEL',
  'DISCARD',
  'DUMP',
  'ECHO',
  'EVAL',
  'EVALSHA',
  'EXEC',
  'EXISTS',
  'EXPIRE',
  'EXPIREAT',
  'FLUSHALL',
  'FLUSHDB',
  'GEOADD',
  'GET',
  'GETBIT',
  'GETDEL',
  'GETEX',
  'GETRANGE',
  'GETSET',
  'HDEL',
  'HEXISTS',
  'HGET',
  'HGETALL',
  'HINCRBY',
  'HINCRBYFLOAT',
  'HKEYS',
  'HLEN',
  'HMGET',
  'HMSET',
  'HSET',
  'HSETNX',
  'HSTRLEN',
  'HVALS',
  'INCR',
  'INCRBY',
  'INCRBYFLOAT',
  'INFO',
  'KEYS',
  'LASTSAVE',
  'LINDEX',
  'LINSERT',
  'LLEN',
  'LPOP',
  'LPUSH',
  'LPUSHX',
  'LRANGE',
  'LREM',
  'LSET',
  'LTRIM',
  'MEMORY',
  'MGET',
  'MIGRATE',
  'MONITOR',
  'MOVE',
  'MSET',
  'MSETNX',
  'MULTI',
  'OBJECT',
  'PERSIST',
  'PEXPIRE',
  'PEXPIREAT',
  'PING',
  'PSETEX',
  'PTTL',
  'PUBLISH',
  'RANDOMKEY',
  'RENAME',
  'RENAMENX',
  'RESTORE',
  'RPOP',
  'RPOPLPUSH',
  'RPUSH',
  'RPUSHX',
  'SADD',
  'SAVE',
  'SCAN',
  'SCARD',
  'SCRIPT',
  'SDIFF',
  'SELECT',
  'SET',
  'SETBIT',
  'SETEX',
  'SETNX',
  'SETRANGE',
  'SHUTDOWN',
  'SINTER',
  'SISMEMBER',
  'SLOWLOG',
  'SMEMBERS',
  'SMISMEMBER',
  'SMOVE',
  'SORT',
  'SPOP',
  'SRANDMEMBER',
  'SREM',
  'SSCAN',
  'STRLEN',
  'SUBSCRIBE',
  'SUNION',
  'TIME',
  'TOUCH',
  'TTL',
  'TYPE',
  'UNLINK',
  'UNSUBSCRIBE',
  'UNWATCH',
  'WATCH',
  'XACK',
  'XADD',
  'XDEL',
  'XGROUP',
  'XINFO',
  'XLEN',
  'XPENDING',
  'XRANGE',
  'XREAD',
  'XREADGROUP',
  'XREVRANGE',
  'XTRIM',
  'ZADD',
  'ZCARD',
  'ZCOUNT',
  'ZINCRBY',
  'ZINTER',
  'ZLEXCOUNT',
  'ZPOPMAX',
  'ZPOPMIN',
  'ZRANGE',
  'ZRANGEBYSCORE',
  'ZRANK',
  'ZREM',
  'ZREMRANGEBYRANK',
  'ZREMRANGEBYSCORE',
  'ZREVRANGE',
  'ZREVRANK',
  'ZSCAN',
  'ZSCORE',
  'ZUNION',
] as const;

/** Prefix at cursor for completion (last token on current line). */
export function getCompletionPrefix(text: string, cursor: number): string {
  const lineStart = text.lastIndexOf('\n', Math.max(0, cursor - 1)) + 1;
  const linePrefix = text.slice(lineStart, cursor);
  const match = linePrefix.match(/(?:^|\s)(\S*)$/);
  return match?.[1] ?? '';
}

/** Match commands first, then key names; case-insensitive prefix. */
export function filterCompletions(
  prefix: string,
  commands: readonly string[],
  keys: readonly string[],
): string[] {
  if (!prefix) return [];

  const needle = prefix.toLowerCase();
  const commandMatches = commands.filter((cmd) =>
    cmd.toLowerCase().startsWith(needle),
  );
  const keyMatches = keys.filter((key) =>
    key.toLowerCase().startsWith(needle),
  );

  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of [...commandMatches, ...keyMatches]) {
    const normalized = item.toLowerCase();
    if (seen.has(normalized)) continue;
    seen.add(normalized);
    out.push(item);
  }
  return out;
}
